# CMake generated Testfile for 
# Source directory: C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests
# Build directory: C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_t0001 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/t0001.exe")
  set_tests_properties(c_t0001 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_t0001 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/t0001.exe")
  set_tests_properties(c_t0001 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_t0001 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/t0001.exe")
  set_tests_properties(c_t0001 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_t0001 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/t0001.exe")
  set_tests_properties(c_t0001 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_t0001 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_t0002 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/t0002.exe")
  set_tests_properties(c_t0002 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_t0002 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/t0002.exe")
  set_tests_properties(c_t0002 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_t0002 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/t0002.exe")
  set_tests_properties(c_t0002 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_t0002 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/t0002.exe")
  set_tests_properties(c_t0002 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_t0002 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_t0003 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/t0003.exe")
  set_tests_properties(c_t0003 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_t0003 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/t0003.exe")
  set_tests_properties(c_t0003 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_t0003 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/t0003.exe")
  set_tests_properties(c_t0003 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_t0003 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/t0003.exe")
  set_tests_properties(c_t0003 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_t0003 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_t0004 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/t0004.exe")
  set_tests_properties(c_t0004 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_t0004 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/t0004.exe")
  set_tests_properties(c_t0004 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_t0004 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/t0004.exe")
  set_tests_properties(c_t0004 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_t0004 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/t0004.exe")
  set_tests_properties(c_t0004 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_t0004 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_t0005 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/t0005.exe")
  set_tests_properties(c_t0005 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_t0005 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/t0005.exe")
  set_tests_properties(c_t0005 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_t0005 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/t0005.exe")
  set_tests_properties(c_t0005 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_t0005 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/t0005.exe")
  set_tests_properties(c_t0005 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_t0005 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_cs_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/cs_convert.exe")
  set_tests_properties(c_cs_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_cs_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/cs_convert.exe")
  set_tests_properties(c_cs_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_cs_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/cs_convert.exe")
  set_tests_properties(c_cs_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_cs_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/cs_convert.exe")
  set_tests_properties(c_cs_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_cs_convert NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_t0007 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/t0007.exe")
  set_tests_properties(c_t0007 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_t0007 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/t0007.exe")
  set_tests_properties(c_t0007 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_t0007 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/t0007.exe")
  set_tests_properties(c_t0007 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_t0007 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/t0007.exe")
  set_tests_properties(c_t0007 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_t0007 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_t0008 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/t0008.exe")
  set_tests_properties(c_t0008 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_t0008 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/t0008.exe")
  set_tests_properties(c_t0008 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_t0008 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/t0008.exe")
  set_tests_properties(c_t0008 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_t0008 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/t0008.exe")
  set_tests_properties(c_t0008 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_t0008 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_t0009 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/t0009.exe")
  set_tests_properties(c_t0009 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_t0009 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/t0009.exe")
  set_tests_properties(c_t0009 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_t0009 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/t0009.exe")
  set_tests_properties(c_t0009 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_t0009 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/t0009.exe")
  set_tests_properties(c_t0009 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_t0009 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_connect_fail "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/connect_fail.exe")
  set_tests_properties(c_connect_fail PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_connect_fail "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/connect_fail.exe")
  set_tests_properties(c_connect_fail PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_connect_fail "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/connect_fail.exe")
  set_tests_properties(c_connect_fail PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_connect_fail "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/connect_fail.exe")
  set_tests_properties(c_connect_fail PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_connect_fail NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_ct_options "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/ct_options.exe")
  set_tests_properties(c_ct_options PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_ct_options "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/ct_options.exe")
  set_tests_properties(c_ct_options PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_ct_options "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/ct_options.exe")
  set_tests_properties(c_ct_options PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_ct_options "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/ct_options.exe")
  set_tests_properties(c_ct_options PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_ct_options NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_lang_ct_param "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/lang_ct_param.exe")
  set_tests_properties(c_lang_ct_param PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_lang_ct_param "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/lang_ct_param.exe")
  set_tests_properties(c_lang_ct_param PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_lang_ct_param "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/lang_ct_param.exe")
  set_tests_properties(c_lang_ct_param PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_lang_ct_param "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/lang_ct_param.exe")
  set_tests_properties(c_lang_ct_param PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_lang_ct_param NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_array_bind "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/array_bind.exe")
  set_tests_properties(c_array_bind PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_array_bind "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/array_bind.exe")
  set_tests_properties(c_array_bind PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_array_bind "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/array_bind.exe")
  set_tests_properties(c_array_bind PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_array_bind "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/array_bind.exe")
  set_tests_properties(c_array_bind PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_array_bind NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_cs_diag "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/cs_diag.exe")
  set_tests_properties(c_cs_diag PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_cs_diag "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/cs_diag.exe")
  set_tests_properties(c_cs_diag PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_cs_diag "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/cs_diag.exe")
  set_tests_properties(c_cs_diag PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_cs_diag "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/cs_diag.exe")
  set_tests_properties(c_cs_diag PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_cs_diag NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_get_send_data "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/get_send_data.exe")
  set_tests_properties(c_get_send_data PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_get_send_data "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/get_send_data.exe")
  set_tests_properties(c_get_send_data PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_get_send_data "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/get_send_data.exe")
  set_tests_properties(c_get_send_data PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_get_send_data "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/get_send_data.exe")
  set_tests_properties(c_get_send_data PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_get_send_data NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_rpc_ct_param "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/rpc_ct_param.exe")
  set_tests_properties(c_rpc_ct_param PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_rpc_ct_param "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/rpc_ct_param.exe")
  set_tests_properties(c_rpc_ct_param PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_rpc_ct_param "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/rpc_ct_param.exe")
  set_tests_properties(c_rpc_ct_param PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_rpc_ct_param "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/rpc_ct_param.exe")
  set_tests_properties(c_rpc_ct_param PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_rpc_ct_param NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_rpc_ct_setparam "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/rpc_ct_setparam.exe")
  set_tests_properties(c_rpc_ct_setparam PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_rpc_ct_setparam "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/rpc_ct_setparam.exe")
  set_tests_properties(c_rpc_ct_setparam PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_rpc_ct_setparam "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/rpc_ct_setparam.exe")
  set_tests_properties(c_rpc_ct_setparam PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_rpc_ct_setparam "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/rpc_ct_setparam.exe")
  set_tests_properties(c_rpc_ct_setparam PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_rpc_ct_setparam NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_ct_diagclient "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/ct_diagclient.exe")
  set_tests_properties(c_ct_diagclient PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_ct_diagclient "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/ct_diagclient.exe")
  set_tests_properties(c_ct_diagclient PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_ct_diagclient "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/ct_diagclient.exe")
  set_tests_properties(c_ct_diagclient PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_ct_diagclient "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/ct_diagclient.exe")
  set_tests_properties(c_ct_diagclient PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_ct_diagclient NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_ct_diagserver "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/ct_diagserver.exe")
  set_tests_properties(c_ct_diagserver PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_ct_diagserver "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/ct_diagserver.exe")
  set_tests_properties(c_ct_diagserver PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_ct_diagserver "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/ct_diagserver.exe")
  set_tests_properties(c_ct_diagserver PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_ct_diagserver "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/ct_diagserver.exe")
  set_tests_properties(c_ct_diagserver PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_ct_diagserver NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_ct_diagall "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/ct_diagall.exe")
  set_tests_properties(c_ct_diagall PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_ct_diagall "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/ct_diagall.exe")
  set_tests_properties(c_ct_diagall PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_ct_diagall "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/ct_diagall.exe")
  set_tests_properties(c_ct_diagall PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_ct_diagall "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/ct_diagall.exe")
  set_tests_properties(c_ct_diagall PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_ct_diagall NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_cs_config "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/cs_config.exe")
  set_tests_properties(c_cs_config PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_cs_config "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/cs_config.exe")
  set_tests_properties(c_cs_config PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_cs_config "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/cs_config.exe")
  set_tests_properties(c_cs_config PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_cs_config "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/cs_config.exe")
  set_tests_properties(c_cs_config PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_cs_config NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_cancel "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/cancel.exe")
  set_tests_properties(c_cancel PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_cancel "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/cancel.exe")
  set_tests_properties(c_cancel PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_cancel "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/cancel.exe")
  set_tests_properties(c_cancel PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_cancel "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/cancel.exe")
  set_tests_properties(c_cancel PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_cancel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_blk_in "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/blk_in.exe")
  set_tests_properties(c_blk_in PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_blk_in "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/blk_in.exe")
  set_tests_properties(c_blk_in PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_blk_in "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/blk_in.exe")
  set_tests_properties(c_blk_in PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_blk_in "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/blk_in.exe")
  set_tests_properties(c_blk_in PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_blk_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_blk_out "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/blk_out.exe")
  set_tests_properties(c_blk_out PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_blk_out "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/blk_out.exe")
  set_tests_properties(c_blk_out PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_blk_out "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/blk_out.exe")
  set_tests_properties(c_blk_out PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_blk_out "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/blk_out.exe")
  set_tests_properties(c_blk_out PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_blk_out NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_ct_cursor "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/ct_cursor.exe")
  set_tests_properties(c_ct_cursor PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_ct_cursor "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/ct_cursor.exe")
  set_tests_properties(c_ct_cursor PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_ct_cursor "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/ct_cursor.exe")
  set_tests_properties(c_ct_cursor PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_ct_cursor "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/ct_cursor.exe")
  set_tests_properties(c_ct_cursor PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_ct_cursor NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_ct_cursors "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/ct_cursors.exe")
  set_tests_properties(c_ct_cursors PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_ct_cursors "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/ct_cursors.exe")
  set_tests_properties(c_ct_cursors PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_ct_cursors "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/ct_cursors.exe")
  set_tests_properties(c_ct_cursors PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_ct_cursors "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/ct_cursors.exe")
  set_tests_properties(c_ct_cursors PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_ct_cursors NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_ct_dynamic "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/ct_dynamic.exe")
  set_tests_properties(c_ct_dynamic PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_ct_dynamic "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/ct_dynamic.exe")
  set_tests_properties(c_ct_dynamic PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_ct_dynamic "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/ct_dynamic.exe")
  set_tests_properties(c_ct_dynamic PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_ct_dynamic "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/ct_dynamic.exe")
  set_tests_properties(c_ct_dynamic PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_ct_dynamic NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_blk_in2 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/blk_in2.exe")
  set_tests_properties(c_blk_in2 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_blk_in2 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/blk_in2.exe")
  set_tests_properties(c_blk_in2 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_blk_in2 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/blk_in2.exe")
  set_tests_properties(c_blk_in2 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_blk_in2 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/blk_in2.exe")
  set_tests_properties(c_blk_in2 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_blk_in2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_data "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/data.exe")
  set_tests_properties(c_data PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_data "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/data.exe")
  set_tests_properties(c_data PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_data "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/data.exe")
  set_tests_properties(c_data PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_data "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/data.exe")
  set_tests_properties(c_data PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_data NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_datafmt "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/datafmt.exe")
  set_tests_properties(c_datafmt PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_datafmt "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/datafmt.exe")
  set_tests_properties(c_datafmt PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_datafmt "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/datafmt.exe")
  set_tests_properties(c_datafmt PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_datafmt "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/datafmt.exe")
  set_tests_properties(c_datafmt PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_datafmt NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_rpc_fail "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/rpc_fail.exe")
  set_tests_properties(c_rpc_fail PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_rpc_fail "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/rpc_fail.exe")
  set_tests_properties(c_rpc_fail PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_rpc_fail "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/rpc_fail.exe")
  set_tests_properties(c_rpc_fail PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_rpc_fail "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/rpc_fail.exe")
  set_tests_properties(c_rpc_fail PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_rpc_fail NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_row_count "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/row_count.exe")
  set_tests_properties(c_row_count PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_row_count "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/row_count.exe")
  set_tests_properties(c_row_count PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_row_count "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/row_count.exe")
  set_tests_properties(c_row_count PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_row_count "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/row_count.exe")
  set_tests_properties(c_row_count PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_row_count NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_all_types "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/all_types.exe")
  set_tests_properties(c_all_types PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_all_types "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/all_types.exe")
  set_tests_properties(c_all_types PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_all_types "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/all_types.exe")
  set_tests_properties(c_all_types PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_all_types "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/all_types.exe")
  set_tests_properties(c_all_types PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_all_types NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_long_binary "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/long_binary.exe")
  set_tests_properties(c_long_binary PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_long_binary "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/long_binary.exe")
  set_tests_properties(c_long_binary PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_long_binary "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/long_binary.exe")
  set_tests_properties(c_long_binary PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_long_binary "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/long_binary.exe")
  set_tests_properties(c_long_binary PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_long_binary NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_will_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/will_convert.exe")
  set_tests_properties(c_will_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_will_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/will_convert.exe")
  set_tests_properties(c_will_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_will_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/will_convert.exe")
  set_tests_properties(c_will_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_will_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/will_convert.exe")
  set_tests_properties(c_will_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_will_convert NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_variant "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/variant.exe")
  set_tests_properties(c_variant PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_variant "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/variant.exe")
  set_tests_properties(c_variant PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_variant "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/variant.exe")
  set_tests_properties(c_variant PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_variant "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/variant.exe")
  set_tests_properties(c_variant PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_variant NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_errors "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/errors.exe")
  set_tests_properties(c_errors PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_errors "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/errors.exe")
  set_tests_properties(c_errors PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_errors "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/errors.exe")
  set_tests_properties(c_errors PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_errors "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/errors.exe")
  set_tests_properties(c_errors PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_errors NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_ct_command "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/ct_command.exe")
  set_tests_properties(c_ct_command PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_ct_command "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/ct_command.exe")
  set_tests_properties(c_ct_command PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_ct_command "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/ct_command.exe")
  set_tests_properties(c_ct_command PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_ct_command "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/ct_command.exe")
  set_tests_properties(c_ct_command PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_ct_command NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(c_timeout "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Debug/timeout.exe")
  set_tests_properties(c_timeout PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(c_timeout "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/Release/timeout.exe")
  set_tests_properties(c_timeout PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(c_timeout "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/MinSizeRel/timeout.exe")
  set_tests_properties(c_timeout PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(c_timeout "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests/RelWithDebInfo/timeout.exe")
  set_tests_properties(c_timeout PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/ctlib/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;21;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/ctlib/unittests/CMakeLists.txt;0;")
else()
  add_test(c_timeout NOT_AVAILABLE)
endif()
