# CMake generated Testfile for 
# Source directory: C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests
# Build directory: C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_t0001 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/t0001.exe")
  set_tests_properties(t_t0001 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_t0001 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/t0001.exe")
  set_tests_properties(t_t0001 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_t0001 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/t0001.exe")
  set_tests_properties(t_t0001 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_t0001 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/t0001.exe")
  set_tests_properties(t_t0001 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_t0001 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_t0002 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/t0002.exe")
  set_tests_properties(t_t0002 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_t0002 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/t0002.exe")
  set_tests_properties(t_t0002 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_t0002 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/t0002.exe")
  set_tests_properties(t_t0002 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_t0002 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/t0002.exe")
  set_tests_properties(t_t0002 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_t0002 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_t0003 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/t0003.exe")
  set_tests_properties(t_t0003 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_t0003 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/t0003.exe")
  set_tests_properties(t_t0003 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_t0003 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/t0003.exe")
  set_tests_properties(t_t0003 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_t0003 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/t0003.exe")
  set_tests_properties(t_t0003 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_t0003 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_t0004 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/t0004.exe")
  set_tests_properties(t_t0004 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_t0004 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/t0004.exe")
  set_tests_properties(t_t0004 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_t0004 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/t0004.exe")
  set_tests_properties(t_t0004 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_t0004 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/t0004.exe")
  set_tests_properties(t_t0004 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_t0004 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_t0005 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/t0005.exe")
  set_tests_properties(t_t0005 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_t0005 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/t0005.exe")
  set_tests_properties(t_t0005 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_t0005 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/t0005.exe")
  set_tests_properties(t_t0005 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_t0005 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/t0005.exe")
  set_tests_properties(t_t0005 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_t0005 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_t0006 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/t0006.exe")
  set_tests_properties(t_t0006 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_t0006 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/t0006.exe")
  set_tests_properties(t_t0006 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_t0006 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/t0006.exe")
  set_tests_properties(t_t0006 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_t0006 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/t0006.exe")
  set_tests_properties(t_t0006 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_t0006 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_t0007 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/t0007.exe")
  set_tests_properties(t_t0007 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_t0007 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/t0007.exe")
  set_tests_properties(t_t0007 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_t0007 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/t0007.exe")
  set_tests_properties(t_t0007 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_t0007 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/t0007.exe")
  set_tests_properties(t_t0007 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_t0007 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_t0008 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/t0008.exe")
  set_tests_properties(t_t0008 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_t0008 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/t0008.exe")
  set_tests_properties(t_t0008 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_t0008 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/t0008.exe")
  set_tests_properties(t_t0008 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_t0008 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/t0008.exe")
  set_tests_properties(t_t0008 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_t0008 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_dynamic1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/dynamic1.exe")
  set_tests_properties(t_dynamic1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_dynamic1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/dynamic1.exe")
  set_tests_properties(t_dynamic1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_dynamic1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/dynamic1.exe")
  set_tests_properties(t_dynamic1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_dynamic1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/dynamic1.exe")
  set_tests_properties(t_dynamic1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_dynamic1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/convert.exe")
  set_tests_properties(t_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/convert.exe")
  set_tests_properties(t_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/convert.exe")
  set_tests_properties(t_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_convert "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/convert.exe")
  set_tests_properties(t_convert PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_convert NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_dataread "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/dataread.exe")
  set_tests_properties(t_dataread PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_dataread "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/dataread.exe")
  set_tests_properties(t_dataread PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_dataread "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/dataread.exe")
  set_tests_properties(t_dataread PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_dataread "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/dataread.exe")
  set_tests_properties(t_dataread PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_dataread NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_utf8_1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/utf8_1.exe")
  set_tests_properties(t_utf8_1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_utf8_1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/utf8_1.exe")
  set_tests_properties(t_utf8_1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_utf8_1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/utf8_1.exe")
  set_tests_properties(t_utf8_1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_utf8_1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/utf8_1.exe")
  set_tests_properties(t_utf8_1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_utf8_1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_utf8_2 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/utf8_2.exe")
  set_tests_properties(t_utf8_2 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_utf8_2 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/utf8_2.exe")
  set_tests_properties(t_utf8_2 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_utf8_2 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/utf8_2.exe")
  set_tests_properties(t_utf8_2 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_utf8_2 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/utf8_2.exe")
  set_tests_properties(t_utf8_2 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_utf8_2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_utf8_3 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/utf8_3.exe")
  set_tests_properties(t_utf8_3 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_utf8_3 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/utf8_3.exe")
  set_tests_properties(t_utf8_3 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_utf8_3 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/utf8_3.exe")
  set_tests_properties(t_utf8_3 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_utf8_3 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/utf8_3.exe")
  set_tests_properties(t_utf8_3 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_utf8_3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_numeric "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/numeric.exe")
  set_tests_properties(t_numeric PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_numeric "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/numeric.exe")
  set_tests_properties(t_numeric PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_numeric "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/numeric.exe")
  set_tests_properties(t_numeric PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_numeric "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/numeric.exe")
  set_tests_properties(t_numeric PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_numeric NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_iconv_fread "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/iconv_fread.exe")
  set_tests_properties(t_iconv_fread PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_iconv_fread "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/iconv_fread.exe")
  set_tests_properties(t_iconv_fread PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_iconv_fread "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/iconv_fread.exe")
  set_tests_properties(t_iconv_fread PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_iconv_fread "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/iconv_fread.exe")
  set_tests_properties(t_iconv_fread PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_iconv_fread NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_toodynamic "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/toodynamic.exe")
  set_tests_properties(t_toodynamic PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_toodynamic "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/toodynamic.exe")
  set_tests_properties(t_toodynamic PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_toodynamic "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/toodynamic.exe")
  set_tests_properties(t_toodynamic PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_toodynamic "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/toodynamic.exe")
  set_tests_properties(t_toodynamic PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_toodynamic NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_readconf "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/readconf.exe")
  set_tests_properties(t_readconf PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_readconf "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/readconf.exe")
  set_tests_properties(t_readconf PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_readconf "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/readconf.exe")
  set_tests_properties(t_readconf PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_readconf "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/readconf.exe")
  set_tests_properties(t_readconf PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_readconf NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_charconv "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/charconv.exe")
  set_tests_properties(t_charconv PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_charconv "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/charconv.exe")
  set_tests_properties(t_charconv PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_charconv "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/charconv.exe")
  set_tests_properties(t_charconv PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_charconv "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/charconv.exe")
  set_tests_properties(t_charconv PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_charconv NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_nulls "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/nulls.exe")
  set_tests_properties(t_nulls PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_nulls "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/nulls.exe")
  set_tests_properties(t_nulls PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_nulls "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/nulls.exe")
  set_tests_properties(t_nulls PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_nulls "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/nulls.exe")
  set_tests_properties(t_nulls PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_nulls NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_corrupt "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/corrupt.exe")
  set_tests_properties(t_corrupt PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_corrupt "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/corrupt.exe")
  set_tests_properties(t_corrupt PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_corrupt "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/corrupt.exe")
  set_tests_properties(t_corrupt PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_corrupt "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/corrupt.exe")
  set_tests_properties(t_corrupt PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_corrupt NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_declarations "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/declarations.exe")
  set_tests_properties(t_declarations PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_declarations "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/declarations.exe")
  set_tests_properties(t_declarations PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_declarations "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/declarations.exe")
  set_tests_properties(t_declarations PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_declarations "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/declarations.exe")
  set_tests_properties(t_declarations PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_declarations NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_portconf "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/portconf.exe")
  set_tests_properties(t_portconf PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_portconf "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/portconf.exe")
  set_tests_properties(t_portconf PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_portconf "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/portconf.exe")
  set_tests_properties(t_portconf PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_portconf "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/portconf.exe")
  set_tests_properties(t_portconf PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_portconf NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_parsing "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/parsing.exe")
  set_tests_properties(t_parsing PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_parsing "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/parsing.exe")
  set_tests_properties(t_parsing PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_parsing "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/parsing.exe")
  set_tests_properties(t_parsing PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_parsing "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/parsing.exe")
  set_tests_properties(t_parsing PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_parsing NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_freeze "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/freeze.exe")
  set_tests_properties(t_freeze PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_freeze "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/freeze.exe")
  set_tests_properties(t_freeze PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_freeze "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/freeze.exe")
  set_tests_properties(t_freeze PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_freeze "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/freeze.exe")
  set_tests_properties(t_freeze PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_freeze NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_strftime "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/strftime.exe")
  set_tests_properties(t_strftime PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_strftime "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/strftime.exe")
  set_tests_properties(t_strftime PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_strftime "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/strftime.exe")
  set_tests_properties(t_strftime PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_strftime "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/strftime.exe")
  set_tests_properties(t_strftime PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_strftime NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_log_elision "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/log_elision.exe")
  set_tests_properties(t_log_elision PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_log_elision "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/log_elision.exe")
  set_tests_properties(t_log_elision PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_log_elision "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/log_elision.exe")
  set_tests_properties(t_log_elision PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_log_elision "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/log_elision.exe")
  set_tests_properties(t_log_elision PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_log_elision NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_convert_bounds "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/convert_bounds.exe")
  set_tests_properties(t_convert_bounds PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_convert_bounds "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/convert_bounds.exe")
  set_tests_properties(t_convert_bounds PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_convert_bounds "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/convert_bounds.exe")
  set_tests_properties(t_convert_bounds PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_convert_bounds "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/convert_bounds.exe")
  set_tests_properties(t_convert_bounds PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_convert_bounds NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(t_tls "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Debug/tls.exe")
  set_tests_properties(t_tls PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(t_tls "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/Release/tls.exe")
  set_tests_properties(t_tls PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(t_tls "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/MinSizeRel/tls.exe")
  set_tests_properties(t_tls PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(t_tls "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests/RelWithDebInfo/tls.exe")
  set_tests_properties(t_tls PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/tds/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;13;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/tds/unittests/CMakeLists.txt;0;")
else()
  add_test(t_tls NOT_AVAILABLE)
endif()
