// -*- C++ -*-
//
// generated by wxGlade 1.0.4 on Sat Apr 15 17:33:52 2023
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "database.h"
#include "createviewoptions.h"

// begin wxGlade: ::extracode
// end wxGlade



CreateViewOptions::CreateViewOptions(wxWindow* parent, const Database *db):
    wxDialog(parent, wxID_ANY, "")
{
    SetTitle( _( "CREATE VIEW options" ) );
    // begin wxGlade: CreateViewOptions::CreateViewOptions
    wxBoxSizer* sizer_1 = new wxBoxSizer( wxHORIZONTAL );
    m_panel = new wxPanel( this, wxID_ANY );
    sizer_1->Add( m_panel, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_2 = new wxBoxSizer( wxHORIZONTAL );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_3 = new wxBoxSizer( wxVERTICAL );
    sizer_2->Add( sizer_3, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_4 = new wxBoxSizer( wxHORIZONTAL );
    sizer_3->Add( sizer_4, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_6 = new wxBoxSizer( wxVERTICAL );
    sizer_4->Add( sizer_6, 0, wxEXPAND, 0 );
    m_temp = new wxCheckBox( m_panel, wxID_ANY, _( "Temporary" ) );
    sizer_6->Add( m_temp, 0, wxEXPAND, 0 );
    sizer_6->Add( 5, 5, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_7 = new wxBoxSizer( wxHORIZONTAL );
    sizer_6->Add( sizer_7, 0, wxEXPAND, 0 );
    wxStaticText* label_1 = new wxStaticText( m_panel, wxID_ANY, _( "In schema:" ) );
    sizer_7->Add( label_1, 0, wxALIGN_CENTER_VERTICAL, 0 );
    sizer_7->Add( 5, 5, 0, wxEXPAND, 0 );
    const wxString m_schemas_choices[] = {};
    m_schemas = new wxComboBox( m_panel, wxID_ANY, _( "" ), wxDefaultPosition, wxDefaultSize, 0, m_schemas_choices, wxCB_DROPDOWN );
    sizer_7->Add( m_schemas, 0, wxALIGN_CENTER_VERTICAL, 0 );
    sizer_4->Add( 5, 5, 0, wxEXPAND, 0 );
    if( db->GetTableVector().m_type == L"Microsoft SQL Server" || ( db->GetTableVector().m_type == L"ODBC" && db->GetTableVector().m_subtype == L"Microsoft SQL Server") )
    {
        wxBoxSizer* sizer_8 = new wxBoxSizer( wxHORIZONTAL );
        sizer_6->Add( sizer_8, 0, wxEXPAND, 0 );
        wxStaticBoxSizer* sizer_9 = new wxStaticBoxSizer( new
                                                     wxStaticBox( m_panel, wxID_ANY, _( "View Attributes" ) ), wxVERTICAL );
        sizer_8->Add( sizer_9, 0, wxEXPAND, 0 );
        sizer_9->Add( 5, 5, 0, wxEXPAND, 0 );
        m_encryotion = new wxCheckBox( m_panel, wxID_ANY, _( "Encryption" ) );
        sizer_9->Add( m_encryotion, 0, wxALIGN_CENTER_HORIZONTAL, 0 );
        sizer_9->Add( 5, 5, 0, wxEXPAND, 0 );
        m_schemaBinding = new wxCheckBox( m_panel, wxID_ANY, _( "Schema Binding" ) );
        sizer_9->Add( m_schemaBinding, 0, wxALIGN_CENTER_HORIZONTAL, 0 );
        sizer_9->Add( 5, 5, 0, wxEXPAND, 0 );
        m_viewMetadata = new wxCheckBox( m_panel, wxID_ANY, _( "View Metadata" ) );
        sizer_9->Add( m_viewMetadata, 0, wxALIGN_CENTER_HORIZONTAL, 0 );
        sizer_9->Add( 5, 5, 0, wxEXPAND, 0 );
        sizer_8->Add( 5, 5, 0, wxEXPAND, 0 );
        m_withCheck = new wxCheckBox( m_panel, wxID_ANY, _( "With Check Option" ) );
        sizer_8->Add( m_withCheck, 0, wxALIGN_CENTER_VERTICAL, 0 );
    }
    sizer_6->Add( 5, 5, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_5 = new wxBoxSizer( wxVERTICAL );
    sizer_4->Add( sizer_5, 1, wxEXPAND, 0 );
    m_ok = new wxButton( m_panel, wxID_OK, _( "OK" ) );
    m_ok->SetDefault();
    sizer_5->Add( m_ok, 0, wxALIGN_CENTER_HORIZONTAL, 0 );
    sizer_5->Add( 5, 5, 0, wxEXPAND, 0 );
    m_cancel = new wxButton( m_panel, wxID_CANCEL, _( "Cancel" ) );
    sizer_5->Add( m_cancel, 0, wxALIGN_CENTER_HORIZONTAL, 0 );
    sizer_5->Add( 5, 5, 0, wxEXPAND, 0 );
    m_help = new wxButton( m_panel, wxID_HELP, _( "Help" ) );
    sizer_5->Add( m_help, 0, wxALIGN_CENTER_HORIZONTAL, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    
    m_panel->SetSizer( sizer_2 );
    SetSizer( sizer_1 );
    sizer_1->Fit( this );
    Layout();
    Centre();
    // end wxGlade
}

