// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Sun Oct 30 13:18:41 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef CREATEINDEX_H
#define CREATEINDEX_H

class CreateIndex: public wxDialog
{
public:
    // begin wxGlade: CreateIndex::ids
    // end wxGlade

    CreateIndex(wxWindow* parent, wxWindowID id, const wxString& title, DatabaseTable *table, const std::wstring &schemaName, Database *db);
    ~CreateIndex();
    std::wstring &GetCommand();
    const wxTextCtrl *GetIndexNameCtrl();
    void SetCurrentField(const wxString &field);
private:
    std::vector<long> m_selectedItems;
    std::vector<std::wstring> m_fields, m_tableFields, m_includeFields;
    std::wstring m_command, m_dbType, m_dbSubType;
    DatabaseTable *m_dbTable;
    Database *m_db;
    std::wstring m_schema;
    unsigned int m_fillFactor;
    unsigned long m_serverVersion = 0;
    // begin wxGlade: CreateIndex::methods
    void set_properties();
    wxString m_where, m_with, m_clustered = "NONCLUSTERED", m_currentField;
    // end wxGlade

protected:
    void OnFieldSelected(wxListEvent &event);
    void OnFileStreamSelected(wxCommandEvent &event);
    void OnFieldDeselected(wxListEvent &event);
    void OnAdvanced(wxCommandEvent &event);;
    void OnOkShowLog(wxCommandEvent &event);
    void OnColumnName(wxGridEditorCreatedEvent &event);
    bool Verify();
    void OnFillFactorUpdateUI(wxUpdateUIEvent &event);
    void OnFastUpdateUpdateUI(wxUpdateUIEvent &event);
    void OnAlgorythmLockDefault(wxCommandEvent &event);
    void OnAlgorythm(wxCommandEvent &event);
    void OnLock(wxCommandEvent &event);
    void OnPadIndex(wxCommandEvent &event);
    void OnFillFactor(wxCommandEvent &event);
    void GenerateQuery();
    void OnOKUpdateUI(wxUpdateUIEvent &event);
    void OnClusteredUnclustered(wxCommandEvent &event);
    void OnDirection(wxCommandEvent &event);
    void OnIndexFieldsMouseUp(wxMouseEvent &event);
    void OnPostgresFieldSelected(wxPropertyGridEvent &event);
    // begin wxGlade: CreateIndex::attributes
    // end wxGlade*/
    // begin wxGlade: MyDialog::attributes
    wxPanel *panel_1;
    wxStaticText *m_label1;
    wxStaticText *m_tableName;
    wxStaticText *m_label2;
    wxStaticText *m_label7;
    wxTextCtrl *m_indexName;
    wxRadioBox *m_unique;
    wxRadioBox *m_direction;
    FieldWindow *m_indexColumns;
    wxListCtrl *m_table;
    wxComboBox *m_collite;
    wxButton *m_OK;
    wxButton *m_Cancel;
    wxButton *m_logOnly;
    wxButton *m_advanced;
    wxButton *m_help;
    wxCheckBox *m_concurrently, *m_only;
    wxComboBox *m_method;
    wxPropertyGrid *m_tablePg;;
    wxPropertyGridManager *m_manager;
    // end wxGlade

}; // wxGlade: end class


#endif // CREATEINDEX_H
