// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Sun Oct 30 13:18:41 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef CREATEINDEX_H
#define CREATEINDEX_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class CreateIndex: public wxDialog {
public:
    // begin wxGlade: CreateIndex::ids
    // end wxGlade

    CreateIndex(wxWindow* parent, wxWindowID id, const wxString& title, DatabaseTable *table);

private:
    DatabaseTable *m_dbTable;
    // begin wxGlade: CreateIndex::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: CreateIndex::attributes
    wxStaticText* m_label1;
    wxStaticText* m_tableName;
    wxStaticText* m_label2;
    wxTextCtrl* m_indexName;
    wxRadioButton* m_unique;
    wxRadioButton* m_duplicate;
    wxRadioButton* m_ascending;
    wxRadioButton* m_descending;
    wxStaticText* m_label3;
    wxTextCtrl* m_indexColumns;
    wxListCtrl* m_table;
    wxButton* m_OK;
    wxButton* m_logOnly;
    wxButton* m_cancel;
    wxButton* m_help;
    wxPanel* panel_1;
    // end wxGlade
}; // wxGlade: end class


#endif // CREATEINDEX_H
