// -*- C++ -*-
//
// generated by wxGlade 1.0.4 on Sat Apr 15 17:33:52 2023
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef CREATEVIEWOPTIONS_H
#define CREATEVIEWOPTIONS_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade

struct NewViewOptions
{
    bool isTemp;
    wxString schema;
};

class CreateViewOptions: public wxDialog
{
public:
    // begin wxGlade: CreateViewOptions::ids
    // end wxGlade

    CreateViewOptions(wxWindow* parent, const Database *db);

private:
    NewViewOptions options;
    
protected:
    // begin wxGlade: CreateViewOptions::attributes
    wxPanel* m_panel;
    wxCheckBox* m_temp;
    wxComboBox* m_schemas;
    wxCheckBox *m_encryotion, *m_schemaBinding, *m_viewMetadata, *m_withCheck;
    wxButton* m_ok;
    wxButton* m_cancel;
    wxButton* m_help;
    // end wxGlade
}; // wxGlade: end class

#endif // CREATEVIEWOPTIONS_H
