// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Wed Jun 22 22:43:12 2022
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "datasource.h"

// begin wxGlade: ::extracode
// end wxGlade



DataSorces::DataSorces(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, style)
{
    // begin wxGlade: DataSorces::DataSorces
    panel_1 = new wxPanel(this, wxID_ANY);
    m_label = new wxStaticText(panel_1, wxID_ANY, _("Select Data Source"));
    m_OK = new wxButton(panel_1, wxID_OK, wxEmptyString);
    const wxString m_dataSources_choices[] = {};
    m_dataSources = new wxComboBox(panel_1, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, m_dataSources_choices, wxCB_DROPDOWN);
    m_cancel = new wxButton(panel_1, wxID_CANCEL, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DataSorces::set_properties()
{
    // begin wxGlade: DataSorces::set_properties
    SetTitle(_("dialog_1"));
    m_OK->SetDefault();
    // end wxGlade
}


void DataSorces::do_layout()
{
    // begin wxGlade: DataSorces::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(2, 2, 5, 5);
    sizer_2->Add(5, 5, 0, wxEXPAND, 0);
    sizer_3->Add(5, 5, 0, wxEXPAND, 0);
    grid_sizer_1->Add(m_label, 0, wxALIGN_CENTER, 0);
    grid_sizer_1->Add(m_OK, 0, wxEXPAND, 0);
    grid_sizer_1->Add(m_dataSources, 0, 0, 0);
    grid_sizer_1->Add(m_cancel, 0, 0, 0);
    sizer_3->Add(grid_sizer_1, 0, 0, 0);
    sizer_3->Add(5, 5, 0, wxEXPAND, 0);
    sizer_2->Add(sizer_3, 1, 0, 0);
    sizer_2->Add(5, 5, 0, wxEXPAND, 0);
    panel_1->SetSizer(sizer_2);
    sizer_1->Add(panel_1, 1, 0, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

