// -*- C++ -*-
//
// generated by wxGlade 1.0.0a7 on Sun Oct 11 02:03:56 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DETACHDB_H
#define DETACHDB_H

class DetachDB: public wxDialog
{
public:
    // begin wxGlade: DetachDB::ids
    // end wxGlade

    DetachDB(wxWindow* parent);

private:

protected:
    // begin wxGlade: DetachDB::attributes
    wxListBox* m_dblist;
    wxButton* button_OK;
    wxButton* button_CANCEL;
    // end wxGlade
}; // wxGlade: end class


#endif // DETACHDB_H
