// -*- C++ -*-
//
// generated by wxGlade 1.0.0a7 on Sun Oct 11 02:03:56 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DETACHDB_H
#define DETACHDB_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DetachDB: public wxDialog {
public:
    // begin wxGlade: DetachDB::ids
    // end wxGlade

    DetachDB(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:

protected:
    // begin wxGlade: DetachDB::attributes
    wxListBox* m_dblist;
    wxButton* button_OK;
    wxButton* button_CANCEL;
    // end wxGlade
}; // wxGlade: end class


#endif // DETACHDB_H
