// -*- C++ -*-
//
// generated by wxGlade 1.1.0 on Thu Nov 14 15:42:25 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DISPLAYFORMATDEFINITION_H
#define DISPLAYFORMATDEFINITION_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DisplayFormatDefinition: public wxDialog {
public:
    // begin wxGlade: DisplayFormatDefinition::ids
    // end wxGlade

    DisplayFormatDefinition(wxWindow* parent, wxWindowID id, const wxString& title, bool isNew);

private:

protected:
    // begin wxGlade: DisplayFormatDefinition::attributes
    wxPanel* panel_1;
    wxTextCtrl* m_name;
    wxComboBox* m_type;
    wxComboBox* m_format;
    wxTextCtrl* m_test;
    wxButton* m_ok;
    wxButton* m_cancel;
    wxButton* m_testButton;
    wxButton* m_help;
    wxStaticText *m_label1, *m_label2, *m_label3, *m_label4, *m_label5;
    // end wxGlade
}; // wxGlade: end class


#endif // DISPLAYFORMATDEFINITION_H
