// -*- C++ -*-
//
// generated by wxGlade 1.1.0 on Thu Nov 14 15:42:26 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>

#include <memory>
#include "maskededit.h"
#include "database.h"
#include "displayformatdefinition.h"

// begin wxGlade: ::extracode
// end wxGlade



DisplayFormatDefinition::DisplayFormatDefinition(wxWindow* parent, wxWindowID id, const wxString& title, bool isNew, const wxString &type, const wxString &format, const FieldTableDisplayProperties &prop, Database *db):
    wxDialog(parent, id, title)
{
    m_isChanged = false;
    m_isNew = isNew;
    m_fieldType = type;
    m_fieldFormat = format;
    m_db = db;
    // begin wxGlade: DisplayFormatDefinition::DisplayFormatDefinition
    SetTitle( _( "Display Format Definition" ) );
    panel_1 = new wxPanel( this, wxID_ANY );
    wxBoxSizer* sizer_2 = new wxBoxSizer( wxHORIZONTAL );
    wxBoxSizer* sizer_3 = new wxBoxSizer( wxVERTICAL );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_2->Add( sizer_3, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_4 = new wxBoxSizer( wxHORIZONTAL );
    sizer_3->Add( sizer_4, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_5 = new wxBoxSizer( wxHORIZONTAL );
    sizer_4->Add( sizer_5, 0, wxEXPAND, 0 );
    m_label1 = new wxStaticText( panel_1, wxID_ANY, _( "Name" ) );
    sizer_5->Add( m_label1, 0, wxALIGN_CENTER_VERTICAL, 0 );
    sizer_5->Add( 5, 5, 0, wxEXPAND, 0 );
    m_name = new wxTextCtrl( panel_1, wxID_ANY, format );
    if( !isNew )
        m_name->Disable();
    sizer_5->Add( m_name, 0, wxALIGN_CENTER_VERTICAL, 0 );
    sizer_4->Add( 5, 5, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_6 = new wxBoxSizer( wxHORIZONTAL );
    sizer_4->Add( sizer_6, 0, wxEXPAND, 0 );
    m_label2 = new wxStaticText( panel_1, wxID_ANY, _( "Type" ) );
    sizer_6->Add( m_label2, 0, wxALIGN_CENTER_VERTICAL, 0 );
    sizer_6->Add( 5, 5, 0, wxEXPAND, 0 );
    const wxString *m_type_choices = NULL;
    m_type = new wxComboBox( panel_1, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, m_type_choices, wxCB_DROPDOWN );
    m_type->SetValue( type );
    m_type->Disable();
    sizer_6->Add( m_type, 0, wxALIGN_CENTER_VERTICAL, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer( 3, 2, 5, 5 );
    grid_sizer_1->AddGrowableCol( 1, 1 );
    sizer_3->Add( grid_sizer_1, 0, wxEXPAND, 0 );
    m_label3 = new wxStaticText( panel_1, wxID_ANY, _( "Format" ) );
    grid_sizer_1->Add( m_label3, 0, wxALIGN_CENTER_VERTICAL, 0 );
    const wxString *m_format_choices = NULL;
    m_format = new wxComboBox( panel_1, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, m_format_choices, wxCB_DROPDOWN );
    for( auto fmt: prop.m_formats )
    {
        for( auto f: fmt.second )
        {
            m_format->Append( std::get<1>( f ) );
        }
    }
    if( !m_isNew )
        m_format->SetValue( m_fieldFormat );
    grid_sizer_1->Add( m_format, 0, wxALIGN_CENTER_VERTICAL | wxEXPAND, 0 );
    m_label4 = new wxStaticText( panel_1, wxID_ANY, _( "Test Value" ) );
    grid_sizer_1->Add( m_label4, 0, wxALIGN_CENTER_VERTICAL, 0 );
    m_test = new wxTextCtrl( panel_1, wxID_ANY, wxEmptyString );
    grid_sizer_1->Add( m_test, 0, wxEXPAND, 0 );
    m_label5 = new wxStaticText( panel_1, wxID_ANY, _( "Result" ) );
    grid_sizer_1->Add( m_label5, 0, wxALIGN_CENTER_VERTICAL, 0 );
    m_result = new wxStaticText( panel_1, wxID_ANY, wxEmptyString );
    grid_sizer_1->Add( m_result, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_7 = new wxBoxSizer( wxVERTICAL );
    sizer_2->Add( sizer_7, 0, wxEXPAND, 0 );
    m_ok = new wxButton( panel_1, wxID_OK, _( "OK" ) );
    sizer_7->Add( m_ok, 0, 0, 0 );
    sizer_7->Add( 5, 5, 0, wxEXPAND, 0 );
    m_cancel = new wxButton( panel_1, wxID_CANCEL, _( "Cancel" ) );
    sizer_7->Add( m_cancel, 0, 0, 0 );
    sizer_7->Add( 5, 5, 0, wxEXPAND, 0 );
    m_testButton = new wxButton( panel_1, wxID_ANY, _( "Test" ) );
    sizer_7->Add( m_testButton, 0, 0, 0 );
    sizer_7->Add( 5, 5, 0, wxEXPAND, 0 );
    m_help = new wxButton( panel_1, wxID_HELP, _( "Help" ) );
    sizer_7->Add( m_help, 0, 0, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    panel_1->SetSizer( sizer_2 );
    sizer_2->Fit( this );
    Layout();
    m_testMask = new wxMaskedEditText( panel_1, wxID_ANY );
    // end wxGlade
    m_ok->Bind( wxEVT_BUTTON, &DisplayFormatDefinition::OnOK, this );
    m_testButton->Bind( wxEVT_UPDATE_UI, &DisplayFormatDefinition::OnTestUpdateUI, this );
    m_testButton->Bind( wxEVT_BUTTON, &DisplayFormatDefinition::OnTest, this );
}

void DisplayFormatDefinition::OnOK(wxCommandEvent &WXUNUSED(event))
{
    std::vector<std::wstring> errorMsg;
    if( m_name->GetValue().IsEmpty() )
        wxMessageBox( _( "Name field can't be empty" ) );
    else
    {
        ColumnFormatDefinitions format;
        format.m_name = m_name->GetValue().ToStdWstring();
        format.m_format = m_format->GetValue().ToStdWstring();
//        format.m_type = m_fieldType;
        m_db->AddUpdateFormat( m_isNew, format, errorMsg );
        EndModal( wxID_OK );
    }
}

void DisplayFormatDefinition::OnTestUpdateUI( wxUpdateUIEvent &event )
{
    if( m_test->GetValue().IsEmpty() && m_format->GetValue().IsEmpty() )
        event.Enable( false );
    else
        event.Enable( true );
}

void DisplayFormatDefinition::OnTest(wxCommandEvent &WXUNUSED(event))
{
    m_testMask->Clear();
    m_testMask->SetMask( m_format->GetValue() );
    m_testMask->SetValue( m_test->GetValue() );
    wxString value = m_testMask->GetValue().Trim();
    if( value.IsEmpty() )
        m_result->SetLabel( "0" );
    else
        m_result->SetLabel( value );
}
