// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Wed Jan 25 23:33:43 2017
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#pragma once

class DropIndexOptionsDialog : public wxDialog
{
public:
    DropIndexOptionsDialog(wxWindow *parent,  const std::wstring &indexName, const std::wstring &tableName, const std::wstring &type, const std::wstring &subtype, DropIndexOption &options);
    const DropIndexOption &GetOptions() const { return m_options; }
private:
    void OnApply(wxCommandEvent &event);
    void OnPGOptions(wxCommandEvent &event);
    // begin wxGlade: AdvancedDroIndexOptions::attributes
    wxPanel* panel_1;
    wxStaticText *m_label1, *m_label2, *m_label3, *m_label4, *m_label5, *m_label6;
    wxTextCtrl* m_indexName;
    wxTextCtrl* m_tableName;
    wxSpinCtrl* m_maxdop = nullptr;
    wxCheckBox* m_online = nullptr;
    wxTextCtrl* m_moveTo = nullptr;
    wxTextCtrl* m_filestream = nullptr;
    wxCheckBox *m_concurrently = nullptr;
    wxCheckBox *m_cascade = nullptr;
    wxCheckBox *m_restrict = nullptr;
    wxComboBox *m_algorithm = nullptr;
    wxComboBox *m_lockopt = nullptr;
    // end wxGlade
    DropIndexOption m_options;
};
