// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Wed Jan 25 23:33:43 2017
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef FOREIGNKEY_H
#define FOREIGNKEY_H

// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade

class ForeignKeyDialog: public wxDialog
{
public:
    // begin wxGlade: ForeignKeyDialog::ids
    // end wxGlade
    ForeignKeyDialog(wxWindow* parent, wxWindowID id, const wxString& title, DatabaseTable *table, Database *db, const std::vector<FKField *> &foreignKeyFields, bool isView, int matchOptions, const bool logOnly) ;
    ~ForeignKeyDialog();
    bool IsLogOnlyI();
    wxTextCtrl *GetKeyNameCtrl() const;
    std::vector<FKField *> &GetForeignKeyVector();
    const std::vector<std::wstring> &GetForeignKeyFields() const;
    const std::vector<std::wstring> &GetPrimaryKeyFields() const;
    int GetMatchingOptions() const;
    bool IsForeignKeyEdited() const;
    int GetDeleteParam() const;
    int GetUpdateParam() const;
    const std::wstring &GetReferencedTable() const;
    const wxString &GetForeignKeyName() const;
    void OnApplyCommand(wxCommandEvent &event);
    void OnPrimaryKeyTableSelection(wxCommandEvent &event);
    void OnDeleteChanges(wxCommandEvent &event);
    void OnUpdateChanges(wxCommandEvent &event);
    void OnSelectDeselectField(wxMouseEvent &event);
    void OnOkUpdateUI(wxUpdateUIEvent &event);
private:
    std::vector<std::wstring> m_foreignKey, m_primaryKey;
    std::wstring m_refTableName;
    wxString m_fkName;
    int m_delete, m_update;
    DatabaseTable *m_pkTable;
    bool m_isLogOnly, m_isView, m_edited;
    int m_nextKey;
    // begin wxGlade: ForeignKeyDialog::methods
    void set_properties();
    void do_layout();
    Database *m_db;
    DatabaseTable *m_table;
    std::vector<FKField *> m_fkfield;
    int m_match;
    // end wxGlade

protected:
    bool Verify();
    // begin wxGlade: ForeignKeyDialog::attributes
    wxStaticText* m_label1;
    wxTextCtrl* m_foreignKeyName;
    wxStaticText* m_label2;
    wxComboBox* m_primaryKeyTable;
    wxStaticText* m_label3;
    FieldWindow* m_foreignKeyColumnsFields;
    wxTextCtrl *m_foreignKeyColumns;
    wxStaticText* m_label4;
    FieldWindow* m_primaryKeyColumnsFields;
    wxTextCtrl* m_primaryKeyColumns;
    wxButton* m_OK;
    wxButton* m_cancel;
    wxButton* m_help;
    wxButton* m_logOnly;
    wxStaticText* m_label6;
    wxListCtrl* list_ctrl_1;
    wxRadioBox* m_onDelete, *m_onUpdate, *m_matching;
    wxStaticText *m_label5 = nullptr;
    wxTextCtrl *m_matchName = nullptr;
    wxCheckBox *m_deferrable = nullptr, *m_initdefer = nullptr, *m_replication = nullptr;
    // end wxGlade
}; // wxGlade: end class

#endif // FOREIGNKEY_H
