// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Tue Apr 18 20:51:59 2017
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef JOINTYPE_H
#define JOINTYPE_H

class JointType : public wxDialog
{
public:
    JointType(wxWindow* parent, wxWindowID id, const wxString& title, const wxString &origTable, const wxString &refTable, const wxString &origField, const wxString &refField, int type, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE);

private:
    wxString m_origTable, m_refTable, m_origField, m_refField, m_title;
    int m_type;
    // begin wxGlade: MyDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyDialog::attributes
    wxStaticText* m_label;
    wxButton* m_OK;
    wxListCtrl* m_joinType;
    wxButton* m_Cancel;
    wxButton* m_delete;
    wxButton* m_help;
    wxPanel* m_panel;
    // end wxGlade
}; // wxGlade: end class

#endif // JOINTYPE_H
