// -*- C++ -*-
//
// generated by wxGlade 1.1.0 on Mon Dec 16 19:58:10 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef NEWEDITVALDATION_H
#define NEWEDITVALDATION_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade

class NewEditValidator: public wxDialog
{
public:
    // begin wxGlade: NewEditValidator::ids
    // end wxGlade

    NewEditValidator(wxWindow* parent, wxWindowID id, const wxString& title, bool isNew, const wxString &type, Database *db, std::tuple<std::wstring , std::wstring , unsigned int, int, std::wstring> &rule);

private:
    Database *m_db;
    bool m_isNew;
protected:
    void OnOK(wxCommandEvent &event);
    // begin wxGlade: NewEditValidator::attributes
    wxPanel* m_panel;
    wxStaticText* m_label;
    wxTextCtrl* m_name;
    wxStaticText* m_label2;
    wxComboBox* m_type;
    wxStaticText* m_label3;
    wxTextCtrl* m_definition;
    wxButton* m_ok;
    wxButton* m_cancel;
    wxButton* m_help;
    wxStaticText* m_label4;
    wxTextCtrl* m_errorMsg;
    wxButton* m_match;
    wxStaticText* m_label5;
    wxButton* m_callNotes;
    wxListBox* list_box_1;
    // end wxGlade
}; // wxGlade: end class

#endif // NEWEDITVALDATION_H
