// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Mon Nov 28 23:55:36 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef PROPERTIES_H
#define PROPERTIES_H

class PropertiesDialog: public wxDialog
{
public:
    PropertiesDialog(wxWindow* parent, wxWindowID id, const wxString& title, Database *db, int type, void *object, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    TableGeneralProperty *m_page1;
#ifdef __WXMSW__
    CFontPropertyPage *m_page2, *m_page3, *m_page4;
#endif
    int m_type;
    // begin wxGlade: PropertiesDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    void OnApply(wxCommandEvent &event);
    void OnOk(wxCommandEvent &event);
    bool ApplyProperties();
    // begin wxGlade: PropertiesDialog::attributes
    wxNotebook* m_properties;
    // end wxGlade
}; // wxGlade: end class

#endif // PROPERTIES_H
