// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Mon Nov 28 23:55:36 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef PROPERTIES_H
#define PROPERTIES_H

struct TableProperties
{
    wxString m_comment, m_dataFontName, m_headingFontName, m_labelFontName;
    int m_dataFontSize, m_headingFontSize, m_labelFontSize;
    bool m_isDataFontUnderlined, m_isDataFontStriken, m_isHeadingFontUnderlined, m_isHeadingFontStriken, m_isLabelFontUnderlined, m_isLabelFontStrioken;
    bool m_isDataFontBold, m_isDataFontItalic, m_isHeadingFontBold, m_isHeadingFontItalic, m_isLabelFontBold, m_isLabelFontItalic;
};

class PropertiesDialog: public wxDialog
{
public:
    PropertiesDialog(wxWindow* parent, wxWindowID id, const wxString& title, Database *db, int type, void *object, const wxString &tableName, const wxString &schemaName, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    const std::wstring &GetCommand();
    bool IsLogOnly();
    void GetTableProperties();

private:
    TableGeneralProperty *m_page1;
    CFontPropertyPage *m_page2, *m_page3, *m_page4;
    int m_type;
    Database *m_db;
    void *m_object;
    std::wstring m_dbType, m_command;
    bool m_isApplied;
    TableProperties m_tableProperties;
    // begin wxGlade: PropertiesDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    void OnApply(wxCommandEvent &event);
    void OnOk(wxCommandEvent &event);
    bool ApplyProperties();
    // begin wxGlade: PropertiesDialog::attributes
    wxNotebook* m_properties;
    // end wxGlade
}; // wxGlade: end class

wxDECLARE_EVENT(wxEVT_SET_TABLE_PROPERTY, wxCommandEvent);

#endif // PROPERTIES_H
