// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Mon Nov 28 23:55:36 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef PROPERTIES_H
#define PROPERTIES_H

class PropertiesDialog: public wxDialog
{
public:
    PropertiesDialog(wxWindow* parent, wxWindowID id, const wxString& title, PropertiesHandler *handler, wxCriticalSection &cs);
    const std::wstring &GetCommand();
    void GetTableProperties();

private:
    TableGeneralProperty *m_page1;
    CFontPropertyPage *m_page2, *m_page3, *m_page4;
    TablePrimaryKey *m_page5;
    FieldGeneral *m_page6;
    FieldHeader *m_page7;
    DatabaseFieldDisplay *m_page8;
//    DesignLabelGeneral *m_page7;
    BandGeneralProperties *m_page9;
    PointerPropertiesPanel *m_page10;
    DatabaseOptionGeneral *m_page11;
    DatabaseptionsColours *m_page12;
    int m_type;
    std::wstring m_dbType, m_command;
    bool m_isApplied;
//    TableProperties m_tableProperties;
    PropertiesHandler *m_handler;
    wxCriticalSection *pcs;
    // begin wxGlade: PropertiesDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    void OnApply(wxCommandEvent &event);
    void OnApplyUpdateUI(wxUpdateUIEvent &event);
    void OnOk(wxCommandEvent &event);
    bool ApplyProperties();
    // begin wxGlade: PropertiesDialog::attributes
    wxNotebook* m_properties;
    // end wxGlade
}; // wxGlade: end class

wxDECLARE_EVENT(wxEVT_SET_TABLE_PROPERTY, wxCommandEvent);
wxDECLARE_EVENT(wxEVT_SET_FIELD_PROPERTY, wxCommandEvent);

#endif // PROPERTIES_H
