// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Mon Nov 28 23:55:36 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//
// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#ifndef WX_PRECOMP
    #include "wx/wx.h"
    #include "wx/stockitem.h"
#endif

#include <memory>
#include "wx/notebook.h"
#include "wx/bmpcbox.h"
#include "wx/docmdi.h"
#include "wx/filepicker.h"
#include "wx/fontenum.h"
#include "wx/listctrl.h"
#ifdef __WXGTK__
#include "gtk/gtk.h"
#include "wx/nativewin.h"
#endif
#ifdef __WXOSX__
#include "wx/fontpicker.h"
#endif
#ifdef __WXQT__
#include <QFontDialog>
#endif
#include "wxsf/ShapeCanvas.h"
#include "database.h"
#include "configuration.h"
//#include "objectproperties.h"
#include "propertieshandlerbase.h"
#include "guiobjectsproperties.h"
#include "field.h"
#include "fieldwindow.h"
#include "colorcombobox.h"
#include "propertypagebase.h"
#include "databaseoptionsgeneral.h"
#include "databaseoptioncolours.h"
#include "tablegeneral.h"
#include "fontpropertypagebase.h"
#include "tableprimarykey.h"
#include "fieldgeneral.h"
#include "designlabelgeneral.h"
#include "pointerproperty.h"
#include "fieldheader.h"
#include "fieldvalidation.h"
#include "bandgeneral.h"
#include "databasefielddisplay.h"
#include "painterobjects.h"
#include "libraryobjectpropertypage.h"
#include "librarypainteroptionsgeneral.h"
#include "librarypainteroptionsinclude.h"
#include "librarypainteroptionsmgmt.h"
#include "fieldstyles.h"
#include "properties.h"

#if _MSC_VER >= 1900 || !(defined __WXMSW__)
std::mutex Database::Impl::my_mutex;
#endif
const wxEventTypeTag<wxCommandEvent> wxEVT_SET_TABLE_PROPERTY( wxEVT_USER_FIRST + 1 );
const wxEventTypeTag<wxCommandEvent> wxEVT_SET_FIELD_PROPERTY( wxEVT_USER_FIRST + 2 );

PropertiesDialog::PropertiesDialog(wxWindow* parent, wxWindowID id, const wxString& title, PropertiesHandler *handler):
    wxDialog(parent, id, title)
{
    std::vector<std::wstring> errors;
    m_isApplied = false;
    m_handler = handler;
    // begin wxGlade: PropertiesDialog::PropertiesDialog
    m_properties = new wxNotebook( this, wxID_ANY );
    switch( handler->GetType() )
    {
        case DatabaseTablePropertiesType:
        {
/*            PropertiesHandler *prop = dynamic_cast<PropertiesHandler *>( handler );
            TableProperties tableProp = prop->GetProperties( errors ).As<TableProperties>();
            wxFont data_font( tableProp.m_dataFontSize, wxFONTFAMILY_DEFAULT, tableProp.m_dataFontItalic ? wxFONTSTYLE_ITALIC : wxFONTSTYLE_NORMAL, tableProp.m_dataFontWeight ? wxFONTWEIGHT_BOLD : wxFONTWEIGHT_NORMAL, tableProp.m_dataFontUnderline, tableProp.m_dataFontName );
            if( tableProp.m_dataFontStrikethrough )
                data_font.SetStrikethrough( true );
            wxFont heading_font( tableProp.m_headingFontSize, wxFONTFAMILY_DEFAULT, tableProp.m_headingFontItalic ? wxFONTSTYLE_ITALIC : wxFONTSTYLE_NORMAL, tableProp.m_headingFontWeight ? wxFONTWEIGHT_BOLD : wxFONTWEIGHT_NORMAL, tableProp.m_headingFontUnderline, tableProp.m_headingFontName );
            if( tableProp.m_headingFontStrikethrough )
                heading_font.SetStrikethrough( true );
            wxFont label_font( tableProp.m_labelFontSize, wxFONTFAMILY_DEFAULT, tableProp.m_labelFontItalic ? wxFONTSTYLE_ITALIC : wxFONTSTYLE_NORMAL, tableProp.m_labelFontWeight ? wxFONTWEIGHT_BOLD : wxFONTWEIGHT_NORMAL, tableProp.m_labelFontUnderline, tableProp.m_labelFontName );
            if( tableProp.m_labelFontStrikethrough )
                label_font.SetStrikethrough( true );
            FontPropertyPage dataFont;
            dataFont.font = data_font;
            dataFont.text = wxColour( *wxBLACK );
            dataFont.back = wxColour( *wxWHITE );
            FontPropertyPage headingFont;
            headingFont.font = heading_font;
            headingFont.text = wxColour( *wxBLACK );
            headingFont.back = wxColour( *wxWHITE );
            FontPropertyPage labelFont;
            labelFont.font = label_font;
            labelFont.text = wxColour( *wxBLACK );
            labelFont.back = wxColour( *wxWHITE );
            m_page1 = new TableGeneralProperty( m_properties, tableProp.table_name, tableProp.m_owner, tableProp.m_comment, DatabaseTablePropertiesType );
            m_properties->AddPage( m_page1, _( "General" ) );
            m_page2 = new CFontPropertyPage( m_properties, dataFont, false );
            m_page3 = new CFontPropertyPage( m_properties, headingFont, false );
            m_page4 = new CFontPropertyPage( m_properties, labelFont, false );
            m_page5 = new TablePrimaryKey( m_properties, prop->GetTable() );*/
            m_properties->AddPage( m_page2, _( "Data Font" ) );
            m_properties->AddPage( m_page3, _( "Heading Font" ) );
            m_properties->AddPage( m_page4, _( "Label Font" ) );
/*            m_properties->AddPage( m_page5, _( "Primary Key" ) );*/
        }
        break;
        case DatabaseFieldPropertiesType:
        {
            FieldProperties prop = ( handler )->GetProperties().As<FieldProperties>();
            m_page6 = new FieldGeneral( m_properties, prop.m_comment );
            m_properties->AddPage( m_page6, _( "General" ) );
            m_page7 = new FieldHeader( m_properties, prop.m_heading );
            m_properties->AddPage( m_page7, _( "Headers" ) );
            m_page8 = new DatabaseFieldDisplay( m_properties, prop.m_display, handler->GetFieldType(), handler->GetDatabase() );
            m_properties->AddPage( m_page8, _( "Display" ) );
            m_page18 = new FieldValidation( m_properties );
            m_properties->AddPage( m_page18, _( "Validation" ) );
            m_page17 = new FieldStyles( m_properties );
            m_properties->AddPage( m_page17, _( "Edit Style" ) );
        }
        break;
        case DividerPropertiesType:
        {
/*            BandProperties prop = dynamic_cast<DividerPropertiesHandler *>( handler )->GetObjectProperties();
            m_page9 = new BandGeneralProperties( m_properties, prop );
            m_properties->AddPage( m_page9, _( "General" ) );
            m_page10 = new PointerPropertiesPanel( m_properties, prop.m_cursorFile, prop.m_cursor );
            m_properties->AddPage( m_page10, _( "Pointer" ) );*/
        }
        break;
        case DesignPropertiesType:
        {
/*            m_page9 = new DesignGeneral( parent, m_options );
            parent->AddPage( m_page1, _( "General" ) );
            m_page2 = new PointerPropertiesPanel( parent, m_options.cursorName, m_options.cursor );
            parent->AddPage( m_page2, _( "Pointer" ) );
            m_page3 = new PrintSpec( parent );
            parent->AddPage( m_page3, _( "Print Specification" ) );*/
        }
        break;
        case DatabasePropertiesType:
        case QueryPropertiesType:
        {
/*            auto prop = dynamic_cast<DatabaseOptionsHandler *>( handler )->GetObjectProperties();
            m_page11 = new DatabaseOptionGeneral( m_properties, prop.m_general );
            m_properties->AddPage( m_page11, _( "General" ) );
            m_page12 = new DatabaseptionsColours( m_properties, prop.m_colors, handler->GetType() == DatabasePropertiesType ? true : false );
            m_properties->AddPage( m_page12, _( "Colors" ) );*/
        }
        break;
        case LibraryPropertiesType:
        {
/*            auto prop = dynamic_cast<PropertiesHandler *>( handler )->GetLibraryProperties();
            m_page13 = new LibraryObjectPropertyPage( m_properties, prop );
            m_properties->AddPage( m_page13, _( "General" ) );*/
        }
        break;
        case LibraryPainterPropertiesType:
        {
/*            auto prop = dynamic_cast<PropertiesHandler *>( handler )->GetOptions();
            m_page14 = new LibraryPainterOptionsGeneralPage( m_properties, prop->m_general );
            m_properties->AddPage( m_page14, _( "General" ) );
            m_page15 = new LibraryPainterOptionsIncludePage( m_properties, prop->m_include );
            m_properties->AddPage( m_page15, _( "Include" ) );
            m_page16 = new LibraryPainterOptionsMgmtPage( m_properties, prop->m_management );
            m_properties->AddPage( m_page16, _( "Source Mgmt" ) );*/
        }
        break;
    }
//    handler->EditProperies( m_properties );
    set_properties();
    do_layout();
    // end wxGlade
    wxButton *apply = dynamic_cast<wxButton *>( FindWindowById( wxID_APPLY ) );
    wxButton *ok = dynamic_cast<wxButton *>( FindWindowById( wxID_OK ) );
    ok->SetDefault();
    apply->Enable( false );
    apply->Bind( wxEVT_BUTTON, &PropertiesDialog::OnApply, this );
    apply->Bind( wxEVT_UPDATE_UI, &PropertiesDialog::OnApplyUpdateUI, this );
    ok->Bind( wxEVT_BUTTON, &PropertiesDialog::OnOk, this );
}

void PropertiesDialog::set_properties()
{
    // begin wxGlade: PropertiesDialog::set_properties
    // end wxGlade
}

void PropertiesDialog::do_layout()
{
    // begin wxGlade: PropertiesDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer( wxHORIZONTAL );
    wxBoxSizer* sizer_2 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer* sizer_3 = new wxBoxSizer( wxVERTICAL );
    wxSizer* buttonSizer = CreateButtonSizer( wxOK | wxCANCEL | wxAPPLY | wxHELP );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_3->Add( m_properties, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_3->Add( buttonSizer, 0, wxEXPAND, 0 );
    sizer_2->Add( sizer_3, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_1->Add( sizer_2, 0, wxEXPAND, 0 );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    SetSizerAndFit( sizer_1 );
    Layout();
    // end wxGlade
}

void PropertiesDialog::OnApply(wxCommandEvent &WXUNUSED(event))
{
    if( ApplyProperties() )
        dynamic_cast<wxButton *>( FindWindowById( wxID_APPLY ) )->Enable( false );
}

void PropertiesDialog::OnOk(wxCommandEvent &WXUNUSED(event))
{
    if( !m_isApplied )
        ApplyProperties();
    EndModal( wxID_OK );
}

bool PropertiesDialog::ApplyProperties()
{
    wxAny any;
    switch( m_handler->GetType() )
    {
        case DatabaseFieldPropertiesType:
        {
            FieldProperties prop;
            prop.m_comment = m_page6->GetCommentCtrl()->GetValue();
            any = prop;
        }
        break;
    }
    std::vector<std::wstring> errors;
    bool result = true;
    m_handler->ApplyProperties( any );
/*    int res = m_handler->GetProperties( errors );
    if( !res )
    {
        for( size_t i = 0; i < m_properties->GetPageCount(); ++i )
        {
            PropertyPageBase *page = dynamic_cast<PropertyPageBase *>( m_properties->GetPage( i ) );
            page->SetModified( false );
        }
        m_isApplied = true;
    }
    else
    {
        wxMessageBox( "Error setting properties for the table" );
        for( std::vector<std::wstring>::iterator it = errors.begin(); it < errors.end(); ++it )
        {
            wxMessageBox( "Errors are " + (*it) );
        }
        result = false;
    }
/*    if( m_type == DatabaseTableProperties )
    {
        if( !m_isApplied && isModified )
        {
        }
    }*/
/*    if( m_type == DatabaseFieldProperties )
    {
        if( !m_isApplied && isModified )
        {
            static_cast<FieldProperties *>( m_object )->m_comment = m_page5->GetCommentCtrl()->GetValue().ToStdWstring();
            static_cast<FieldProperties *>( m_object )->m_label = m_page6->GetLabelCtrl()->GetValue().ToStdWstring();
            static_cast<FieldProperties *>( m_object )->m_heading = m_page6->GetHeadingCtrl()->GetValue().ToStdWstring();
            wxCommandEvent event( wxEVT_SET_FIELD_PROPERTY );
            event.SetInt( IsLogOnly() );
            event.SetExtraLong( m_type );
            event.SetClientData( &m_object );
            dynamic_cast<wxDocMDIChildFrame *>( GetParent() )->GetView()->ProcessEvent( event );
            if( event.GetString() == "Failed" )
                result = false;
        }
    }*/
    return result;
}

const std::wstring &PropertiesDialog::GetCommand()
{
    return m_command;
}

void PropertiesDialog::OnApplyUpdateUI (wxUpdateUIEvent &event)
{
    for( size_t i = 0; i < m_properties->GetPageCount(); ++i )
    {
        PropertyPageBase *page = dynamic_cast<PropertyPageBase *>( m_properties->GetPage( i ) );
        if( page->IsModified() )
            event.Enable( true );
    }
}
