// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Mon Nov 28 23:55:36 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//
// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#ifndef WX_PRECOMP
    #include "wx/wx.h"
    #include "wx/stockitem.h"
#endif

#include "wx/notebook.h"
#include "database.h"
#include "tablegeneral.h"
#include "properties.h"

PropertiesDialog::PropertiesDialog(wxWindow* parent, wxWindowID id, const wxString& title, Database *db, int type, void *object, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, style)
{
    m_type = type;
    // begin wxGlade: PropertiesDialog::PropertiesDialog
    m_properties = new wxNotebook( this, wxID_ANY );
    if( type == 0 )
    {
        m_page1 = new TableGeneralProperty( m_properties );
        m_properties->AddPage( m_page1, _( "General" ) );
    }
    notebook_1_pane_1 = new wxPanel( m_properties, wxID_ANY );

    set_properties();
    do_layout();
    // end wxGlade
}


void PropertiesDialog::set_properties()
{
    // begin wxGlade: PropertiesDialog::set_properties
//    SetTitle( _( "dialog_1" ) );
    // end wxGlade
}


void PropertiesDialog::do_layout()
{
    // begin wxGlade: PropertiesDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer( wxHORIZONTAL );
    wxBoxSizer* sizer_2 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer* sizer_3 = new wxBoxSizer( wxVERTICAL );
    wxSizer* buttonSizer = CreateButtonSizer( wxOK | wxCANCEL | wxAPPLY | wxHELP );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_3->Add( m_properties, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_3->Add( buttonSizer, 0, wxEXPAND, 0 );
    sizer_2->Add( sizer_3, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_1->Add( sizer_2, 0, wxEXPAND, 0 );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    SetSizer( sizer_1 );
    sizer_1->Fit( this );
    Layout();
    // end wxGlade
}

