// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Wed Jun 29 22:04:47 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef SELECTTABLES_H
#define SELECTTABLES_H

class SelectTables: public wxDialog
{
public:
    SelectTables(wxWindow* parent, wxWindowID id, const wxString& title, Database *db, std::vector<std::wstring> &names, bool isTableView, const int type, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    void GetSelectedTableNames(std::map<wxString, std::vector<TableDefinition> > &tableNames);
private:
    wxBoxSizer* sizer_1;
    Database *m_db;
	std::vector<std::wstring> m_names;
    bool m_isTableView;
    // begin wxGlade: SelectTables::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    void FillTableList(bool sysTableIncluded);
    // begin wxGlade: SelectTables::attributes
    wxListBox* m_tables;
    wxCheckBox* m_showSystem;
    wxCheckBox *m_readOnly;
    wxButton* m_open;
    wxButton* m_new;
    wxButton* m_cancel;
    wxButton* m_help;
    wxPanel* m_panel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

    void OnSelectingLBItem(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnOpenTables(wxCommandEvent &event);
    void OnCancel(wxCommandEvent &event);
    void OnShowSystemTables(wxCommandEvent &event);
}; // wxGlade: end class


#endif // SELECTTABLES_H
