// -*- C++ -*-
//
// generated by wxGlade 1.1.0 on Wed Apr 29 14:13:29 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//
#include "wx/wx.h"
#include "wx/filepicker.h"
#include "sqlserveraddfilespec.h"

// begin wxGlade: ::extracode
// end wxGlade



SQLServerAddFileSpec::SQLServerAddFileSpec(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: SQLServerAddFileSpec::SQLServerAddFileSpec
    SetTitle( "dialog" );
    auto sizer_1 = new wxBoxSizer( wxHORIZONTAL );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    auto sizer_2 = new wxBoxSizer( wxVERTICAL );
    sizer_1->Add( sizer_2, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    auto grid_sizer_1 = new wxFlexGridSizer( 5, 3, 5, 5 );
    sizer_2->Add( grid_sizer_1, 0, wxEXPAND, 0 );
    m_label1 = new wxStaticText( this, wxID_ANY, "Name" );
    grid_sizer_1->Add( m_label1, 0, wxALIGN_CENTER_VERTICAL, 0 );
    m_name = new wxTextCtrl( this, wxID_ANY, wxEmptyString );
    grid_sizer_1->Add( m_name, 0, 0, 0 );
    grid_sizer_1->Add( 5, 5, 0, 0, 0 );
    m_label2 = new wxStaticText( this, wxID_ANY, "FileName" );
    grid_sizer_1->Add( m_label2, 0, wxALIGN_CENTER_VERTICAL, 0 );
    m_fileName = new wxFilePickerCtrl( this, wxID_ANY, wxEmptyString );
    grid_sizer_1->Add( m_fileName, 0, 0, 0 );
    grid_sizer_1->Add( 5, 5, 0, 0, 0 );
    m_label3 = new wxStaticText( this, wxID_ANY, "Size" );
    grid_sizer_1->Add( m_label3, 0, wxALIGN_CENTER_VERTICAL, 0 );
    m_size = new wxTextCtrl( this, wxID_ANY, wxEmptyString );
    grid_sizer_1->Add( m_size, 0, 0, 0 );
    const wxString m_measure1_choices[] = {
        "KB",
        "MB",
        "GB",
        "TB",
    };
    m_measure1 = new wxChoice( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 4, m_measure1_choices );
    m_measure1->SetSelection( 1 );
    grid_sizer_1->Add( m_measure1, 0, 0, 0 );
    m_label4 = new wxStaticText( this, wxID_ANY, "MaxSize" );
    grid_sizer_1->Add( m_label4, 0, wxALIGN_CENTER_VERTICAL, 0 );
    wxBoxSizer* sizer_3 = new wxBoxSizer( wxHORIZONTAL );
    grid_sizer_1->Add( sizer_3, 1, wxEXPAND, 0 );
    m_maxSize = new wxTextCtrl( this, wxID_ANY, wxEmptyString );
    m_maxSize->Enable( false );
    sizer_3->Add( m_maxSize, 0, 0, 0 );
    sizer_3->Add( 5, 5, 0, 0, 0 );
    const wxString m_measure2_choices[] = {
        "KB",
        "MB",
        "GB",
        "TB",
    };
    m_measure2 = new wxChoice( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 4, m_measure2_choices );
    m_measure2->Enable( false );
    m_measure2->SetSelection( 1 );
    sizer_3->Add( m_measure2, 0, 0, 0 );
    checkbox_1 = new wxCheckBox( this, wxID_ANY, "UNLIMITED" );
    checkbox_1->SetValue( 1 );
    grid_sizer_1->Add( checkbox_1, 0, wxALIGN_CENTER_VERTICAL, 0 );
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, "FileGrowth" );
    grid_sizer_1->Add( label_1, 0, 0, 0 );
    m_growth = new wxTextCtrl( this, wxID_ANY, wxEmptyString );
    grid_sizer_1->Add( m_growth, 0, wxEXPAND, 0 );
    const wxString m_measure3_choices[] = {
        "KB",
        "MB",
        "GB",
        "TB",
        "%",
    };
    m_measure3 = new wxChoice( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 5, m_measure3_choices );
    m_measure3->SetSelection( 1 );
    grid_sizer_1->Add( m_measure3, 0, 0, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    auto buttons = CreateStdDialogButtonSizer( wxOK | wxCANCEL | wxHELP );
    sizer_2->Add( buttons, 0, wxEXPAND, 0 );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    
    SetSizer( sizer_1 );
    sizer_1->Fit( this );
    Layout();
    // end wxGlade
}

