// -*- C++ -*-
//
// generated by wxGlade 1.1.0 on Wed Apr 29 14:13:29 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef SQLSERVERADDFILESPEC_H
#define SQLSERVERADDFILESPEC_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class SQLServerAddFileSpec: public wxDialog
{
public:
    // begin wxGlade: SQLServerAddFileSpec::ids
    // end wxGlade

    SQLServerAddFileSpec(wxWindow* parent, wxWindowID id, const wxString& title);

private:

protected:
    // begin wxGlade: SQLServerAddFileSpec::attributes
    wxStaticText* m_label1;
    wxTextCtrl* m_name;
    wxStaticText* m_label2;
    wxFilePickerCtrl * m_fileName;
    wxStaticText* m_label3;
    wxTextCtrl* m_size;
    wxChoice* m_measure1;
    wxStaticText* m_label4;
    wxTextCtrl* m_maxSize;
    wxChoice* m_measure2;
    wxCheckBox* checkbox_1;
    wxTextCtrl* m_growth;
    wxChoice* m_measure3;
    // end wxGlade
    void OnUnlimited(wxCommandEvent &event);
    void OnOKUpdateUI(wxUpdateUIEvent &event);
}; // wxGlade: end class


#endif // SQLSERVERADDFILESPEC_H
