# CMake generated Testfile for 
# Source directory: C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests
# Build directory: C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(u_passarg "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Debug/passarg.exe")
  set_tests_properties(u_passarg PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(u_passarg "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Release/passarg.exe")
  set_tests_properties(u_passarg PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(u_passarg "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/MinSizeRel/passarg.exe")
  set_tests_properties(u_passarg PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(u_passarg "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/RelWithDebInfo/passarg.exe")
  set_tests_properties(u_passarg PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
else()
  add_test(u_passarg NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(u_condition "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Debug/condition.exe")
  set_tests_properties(u_condition PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(u_condition "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Release/condition.exe")
  set_tests_properties(u_condition PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(u_condition "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/MinSizeRel/condition.exe")
  set_tests_properties(u_condition PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(u_condition "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/RelWithDebInfo/condition.exe")
  set_tests_properties(u_condition PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
else()
  add_test(u_condition NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(u_mutex1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Debug/mutex1.exe")
  set_tests_properties(u_mutex1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(u_mutex1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Release/mutex1.exe")
  set_tests_properties(u_mutex1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(u_mutex1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/MinSizeRel/mutex1.exe")
  set_tests_properties(u_mutex1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(u_mutex1 "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/RelWithDebInfo/mutex1.exe")
  set_tests_properties(u_mutex1 PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
else()
  add_test(u_mutex1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(u_dlist "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Debug/dlist.exe")
  set_tests_properties(u_dlist PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(u_dlist "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Release/dlist.exe")
  set_tests_properties(u_dlist PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(u_dlist "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/MinSizeRel/dlist.exe")
  set_tests_properties(u_dlist PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(u_dlist "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/RelWithDebInfo/dlist.exe")
  set_tests_properties(u_dlist PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
else()
  add_test(u_dlist NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(u_bytes "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Debug/bytes.exe")
  set_tests_properties(u_bytes PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(u_bytes "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Release/bytes.exe")
  set_tests_properties(u_bytes PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(u_bytes "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/MinSizeRel/bytes.exe")
  set_tests_properties(u_bytes PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(u_bytes "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/RelWithDebInfo/bytes.exe")
  set_tests_properties(u_bytes PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
else()
  add_test(u_bytes NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(u_smp "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Debug/smp.exe")
  set_tests_properties(u_smp PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(u_smp "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Release/smp.exe")
  set_tests_properties(u_smp PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(u_smp "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/MinSizeRel/smp.exe")
  set_tests_properties(u_smp PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(u_smp "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/RelWithDebInfo/smp.exe")
  set_tests_properties(u_smp PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
else()
  add_test(u_smp NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(u_path "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Debug/path.exe")
  set_tests_properties(u_path PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(u_path "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/Release/path.exe")
  set_tests_properties(u_path PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(u_path "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/MinSizeRel/path.exe")
  set_tests_properties(u_path PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(u_path "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests/RelWithDebInfo/path.exe")
  set_tests_properties(u_path PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/utils/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;11;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/utils/unittests/CMakeLists.txt;0;")
else()
  add_test(u_path NOT_AVAILABLE)
endif()
