// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Wed Jun 22 22:43:12 2022
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DATASOURCE_H
#define DATASOURCE_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade

class DataSorces: public wxDialog
{
public:
    // begin wxGlade: DataSorces::ids
    // end wxGlade

    DataSorces(wxWindow* parent, wxWindowID id, const wxString& title, const std::vector<Profile> &profiles);
    wxString &GetDataSource() { return m_dataSource; }
private:
    // begin wxGlade: DataSorces::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    wxString m_dataSource;
    std::vector<Profile> m_profiles;
protected:
    void OnOK(wxCommandEvent &event);
    // begin wxGlade: DataSorces::attributes
    wxStaticText* m_label;
    wxButton* m_OK;
    wxComboBox* m_dataSources;
    wxButton* m_cancel;
    wxPanel* m_panel;
    // end wxGlade
}; // wxGlade: end class


#endif // DATASOURCE_H
