// -*- C++ -*-
//
// generated by wxGlade 1.0.4 on Wed Apr 26 20:52:38 2023
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef SAVEVIEW_H
#define SAVEVIEW_H

class SaveQuery: public wxDialog
{
public:
    SaveQuery(wxWindow* parent);
    wxTextCtrl *GetNameCtrl() const { return text_ctrl_1; }
private:

protected:
    void OnButtonUpdateUI(wxUpdateUIEvent &event);
    // begin wxGlade: SaveQuery::attributes
    wxPanel* panel_1;
    wxTextCtrl* text_ctrl_1;
    wxButton* button_1;
    wxButton* button_2;
    wxButton* button_3;
    wxButton* button_4;
    // end wxGlade
}; // wxGlade: end class


#endif // SAVEVIEW_H
