# AppVeyor script for wxPdfDocument

image:
  - Visual Studio 2022 

# branches to build
branches:
  only:
    - main

# environments
environment:
  matrix:
  - TOOLSET: msbuild
    CONFIGURATION: Release wxDLL
    ARCH: Win64
#  - TOOLSET: cmake
#    GENERATOR: 'Visual Studio 14.1'
#    SHARED: ON
#    CONFIGURATION: Release

# clone directory
clone_folder: c:\projects\wxpdfdoc

# scripts to run before build
before_build:
  # set environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.4/wxMSW-3.2.4_vc14x_x64_Dev.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.4/wxMSW-3.2.4_vc14x_x64_ReleaseDLL.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.4/wxMSW-3.2.4_vc14x_x64_ReleasePDB.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.4/wxWidgets-3.2.4-headers.7z'
  - cmd: 7z x wxMSW-3.2.4_vc14x_x64_Dev.7z -oC:\wxWidgets -aoa
  - cmd: 7z x wxMSW-3.2.4_vc14x_x64_ReleaseDLL.7z -oC:\wxWidgets -aoa
  - cmd: 7z x wxMSW-3.2.4_vc14x_x64_ReleasePDB.7z -oC:\wxWidgets -aoa
  - cmd: 7z x wxWidgets-3.2.4-headers.7z -oC:\wxWidgets -aoa

# build script
build_script: c:\projects\wxpdfdoc\admin\appveyor\appveyor.bat

# testing
test_script: c:\projects\wxpdfdoc\admin\appveyor\appveyor-test.bat
