// -*- C++ -*-
//
// generated by wxGlade 0.9.2 on Wed Jul 22 22:08:25 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//
#include <wx/wx.h>
#include <wx/image.h>

#include "wx/bmpcbox.h"
#include "wx/valnum.h"
#include "database.h"
#include "guiojectsproperties.h"
#include "colorcombobox.h"
#include "propertypagebase.h"
#include "colorcombobox.h"
#include "bandgeneral.h"

// begin wxGlade: ::extracode
// end wxGlade

BandGeneralPropertiesPage::BandGeneralPropertiesPage(wxWindow* parent,  const BandProperties &props):
    PropertyPageBase(parent)
{
    // begin wxGlade: BandGeneralProperties::BandGeneralProperties
    m_label1 = new wxStaticText( this, wxID_ANY, _( "Color" ) );
    m_colors = new CColorComboBox( this, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, 0, nullptr, wxCB_DROPDOWN );
    m_colors->SetValue( props.m_general.m_color );
    m_label2 = new wxStaticText( this, wxID_ANY, _( "Height" ) );
    m_height = new wxTextCtrl( this, wxID_ANY, wxString::Format( "%d", props.m_general.m_height ) );
    m_autosize = new wxCheckBox( this, wxID_ANY, _( "Autosize Height" ) );

    set_properties();
//    m_autosize->SetValue( props.m_autosize );
    do_layout();
    // end wxGlade
    m_colors->Bind( wxEVT_COMBOBOX, &BandGeneralPropertiesPage::OnPageModified, this );
    m_height->Bind( wxEVT_TEXT, &BandGeneralPropertiesPage::OnPageModified, this );
    m_autosize->Bind( wxEVT_CHECKBOX, &BandGeneralPropertiesPage::OnPageModified, this );
}

void BandGeneralPropertiesPage::set_properties()
{
    // begin wxGlade: BandGeneralProperties::set_properties
    // end wxGlade
}

void BandGeneralPropertiesPage::do_layout()
{
    // begin wxGlade: BandGeneralProperties::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer( wxHORIZONTAL );
    wxBoxSizer* sizer_2 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer* sizer_3 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer* sizer_4 = new wxBoxSizer( wxHORIZONTAL );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_3->Add( m_label1, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_3->Add( m_colors, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 10, 0, wxEXPAND, 0 );
    sizer_3->Add( m_label2, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_4->Add( m_height, 0, wxEXPAND, 0 );
    sizer_4->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_3->Add( sizer_4, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_3->Add( m_autosize, 0, wxEXPAND, 0 );
    sizer_2->Add( sizer_3, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_1->Add( sizer_2, 0, wxEXPAND, 0 );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    SetSizer( sizer_1 );
    sizer_1->Fit( this );
    // end wxGlade
}

void BandGeneralPropertiesPage::OnPageModified(wxCommandEvent &WXUNUSED(event))
{
    PageEdited();
}
