// -*- C++ -*-
//
// generated by wxGlade 0.9.2 on Wed Jul 22 22:08:25 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef BANDGENERAL_H
#define BANDGENERAL_H

class WXEXPORT BandGeneralPropertiesPage: public PropertyPageBase
{
public:
    // begin wxGlade: BandGeneralProperties::ids
    // end wxGlade

    BandGeneralPropertiesPage(wxWindow* parent, const BandProperties &props);
    virtual ~BandGeneralPropertiesPage() {};

private:
    // begin wxGlade: BandGeneralProperties::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    unsigned int m_heightValue;

protected:
    // begin wxGlade: BandGeneralProperties::attributes
    CColorComboBox *m_colors;
    wxTextCtrl *m_height;
    wxStaticText *m_label1, *m_label2;
    wxCheckBox *m_autosize;
    // end wxGlade
    void OnPageModified(wxCommandEvent &event);
}; // wxGlade: end class


#endif // BANDGENERAL_H
