// -*- C++ -*-
//
// generated by wxGlade 0.9.2 on Wed Jul 22 22:08:25 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#pragma once

struct DBOptionGeneral
{
    wxString m_sharedProfile, m_sqlTerminator, m_tableRefresh, m_tableColumns;
    bool m_tableLst, m_useRepo, m_readOnly, m_keepAlive;
};

class WXEXPORT DatabaseOptionGeneral : public wxPanel
{
public:
    DatabaseOptionGeneral(wxWindow *parent);
private:
    wxFilePickerCtrl *m_sharedFolder;
    wxCheckBox *m_displayTableList, *m_useRepository, *m_readOnly, *m_keepAlive;
    wxTextCtrl *m_terminator, *m_refreshTables, *m_colmnsInTable;
    unsigned long m_value;
    DBOptionGeneral m_defaults;
};
