// -*- C++ -*-
//
// generated by wxGlade 0.9.2 on Wed Jul 22 22:08:25 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#pragma once

class WXEXPORT DatabaseptionsColours : public PropertyPageBase
{
public:
    DatabaseptionsColours(wxWindow *parent, const DatabaseOptionColors &colors);
private:
    wxButton *restore;
    CColorComboBox *m_bacground, *m_textCol;
    DatabaseOptionColors m_defaults, m_current;
};