// -*- C++ -*-
//
// generated by wxGlade 1.0.4 on Mon Jan 15 21:11:42 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DATABASEFIELDDISPLAY_H
#define DATABASEFIELDDISPLAY_H

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class WXEXPORT DatabaseFieldDisplay: public PropertyPageBase
{
public:
    // begin wxGlade: DatabaseFieldDisplay::ids
    // end wxGlade

    DatabaseFieldDisplay(wxWindow* parent, wxWindowID id);

private:

protected:
    // begin wxGlade: DatabaseFieldDisplay::attributes
    wxListBox* m_formats;
    wxButton* m_edit;
    wxButton* m_new;
    wxComboBox* m_justify;
    wxTextCtrl* m_height;
    wxTextCtrl* m_width;
    // end wxGlade
}; // wxGlade: end class


#endif // DATABASEFIELDDISPLAY_H
