// -*- C++ -*-
//
// generated by wxGlade 1.0.4 on Mon Jan 15 21:11:42 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DATABASEFIELDDISPLAY_H
#define DATABASEFIELDDISPLAY_H

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif

class WXEXPORT DatabaseFieldDisplay: public PropertyPageBase
{
public:
    // begin wxGlade: DatabaseFieldDisplay::ids
    // end wxGlade

    DatabaseFieldDisplay(wxWindow* parent, const FieldTableDisplayProperties &prop, const wxString &type, Database *db);

private:
    wxString m_type;
    Database *m_db;
protected:
    void OnEditNewFormat(wxCommandEvent &event);
    void OnUpdateUIEditButton(wxUpdateUIEvent &event);
    // begin wxGlade: DatabaseFieldDisplay::attributes
    wxListBox* m_formats;
    wxButton* m_edit;
    wxButton* m_new;
    wxComboBox* m_justify;
    wxTextCtrl* m_height;
    wxTextCtrl* m_width;
    // end wxGlade
    void OnPageModified(wxCommandEvent &event);
}; // wxGlade: end class


#endif // DATABASEFIELDDISPLAY_H
