// -*- C++ -*-
//
// generated by wxGlade 1.0.0a7 on Wed Sep 16 03:34:30 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DESIGNGENERAL_H
#define DESIGNGENERAL_H

class WXEXPORT DesignGeneral: public PropertyPageBase
{
public:
    // begin wxGlade: MyDialog::ids
    // end wxGlade

    DesignGeneral(wxWindow* parent, DesignCanvasGeneralProperties options);
    virtual ~DesignGeneral() { }
    wxComboBox *GetUnitsCtrl() { return m_units; }
    CColorComboBox *GetColorCtrl() { return m_color; }
private:
    void Modified(wxCommandEvent &);
protected:
    // begin wxGlade: MyDialog::attributes
    wxComboBox* m_units, *m_display;
    wxTextCtrl* m_interval;
    CColorComboBox* m_color;
    wxCheckBox *m_custommove, *m_mouseSelect, *m_rowresize;
    // end wxGlade
}; // wxGlade: end class


#endif // DESIGNGENERAL_H
