// -*- C++ -*-
//
// generated by wxGlade 1.1.0 on Sat Nov  9 18:19:35 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef FIELDSTYLES_H
#define FIELDSTYLES_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class WXEXPORT FieldStyles: public PropertyPageBase
{
public:
    // begin wxGlade: MyDialog::ids
    // end wxGlade
    FieldStyles(wxWindow* parent);
private:
    void OnNew(wxCommandEvent &event);
protected:
    // begin wxGlade: MyDialog::attributes
    wxListBox* m_styles;
    wxButton* m_edit;
    wxButton* m_new;
    // end wxGlade
    wxStaticText *m_label1; 
}; // wxGlade: end class

#endif // FIELDSTYLES_H
