// -*- C++ -*-
//
// generated by wxGlade 1.1.0 on Sat Nov  9 22:00:04 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef FIELDVALIDATION_H
#define FIELDVALIDATION_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class WXEXPORT FieldValidation: public PropertyPageBase
{
public:
    // begin wxGlade: FieldValidation::ids
    // end wxGlade

    FieldValidation(wxWindow* parent, Database *db, const wxString &fieldType);

private:
    Database *m_db;
    wxString m_fieldType;
protected:
    // begin wxGlade: FieldValidation::attributes
    wxListBox* m_rules;
    wxButton* m_edit;
    wxButton* m_new;
    wxComboBox* m_initValue;
    // end wxGlade
    wxStaticText *m_label1, *m_label2;
    void OnEditUpdateUI(wxUpdateUIEvent &event);
    void OnButtonPress(wxCommandEvent &event);
}; // wxGlade: end class


#endif // FIELDVALIDATION_H
