// -*- C++ -*-
//
// generated by wxGlade 1.1.0 on Sat Nov  9 18:19:35 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//
#include <wx/wx.h>
#include <wx/image.h>
#include "propertypagebase.h"
#include "fieldstyles.h"

// begin wxGlade: ::extracode
// end wxGlade



FieldStyles::FieldStyles(wxWindow* parent) : PropertyPageBase( parent )
{
    // begin wxGlade: MyDialog::MyDialog
    auto sizer1 = new wxBoxSizer( wxVERTICAL );
    auto sizer2 = new wxBoxSizer( wxHORIZONTAL );
    sizer1->Add( sizer2, 1, wxEXPAND, 0 );
    sizer2->Add( 5, 5, 0, wxEXPAND, 0 );
    auto sizer3 = new wxBoxSizer( wxVERTICAL );
    sizer2->Add( sizer3, 1, wxEXPAND, 0 );
    sizer3->Add( 5, 5, 0, wxEXPAND, 0 );
    auto grid4 = new wxFlexGridSizer( 2, 2, 5, 5 );
    sizer3->Add( grid4, 0, wxEXPAND, 0 );
    wxStaticText* m_label = new wxStaticText( this, wxID_ANY, _( "Style Names:" ) );
    grid4->Add( m_label, 0, wxEXPAND, 0 );
    grid4->Add( 5, 5, 0, wxEXPAND, 0 );
    m_styles = new wxListBox( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, nullptr, wxLB_SINGLE );
    grid4->Add( m_styles, 0, wxEXPAND, 0 );
    auto sizer5 = new wxBoxSizer( wxVERTICAL );
    grid4->Add(sizer5, 0, wxEXPAND, 0);
    m_edit = new wxButton( this, wxID_ANY, _( "&Edit..." ) );
    sizer5->Add( m_edit, 0, wxEXPAND, 0 );
    sizer5->Add( 5, 5, 0, wxEXPAND, 0 );
    m_new = new wxButton( this, wxID_ANY, _( "&New" ) );
    sizer5->Add( m_new, 0, wxEXPAND, 0 );
    sizer3->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer2->Add( 5, 5, 0, wxEXPAND, 0 );
    
    grid4->AddGrowableRow( 0 );
    grid4->AddGrowableRow( 1 );
    grid4->AddGrowableCol( 0 );
    grid4->AddGrowableCol( 1 );
    SetSizer( sizer1 );
    sizer1->Fit( this );
    // end wxGlade
}

