// -*- C++ -*-
//
// generated by wxGlade 1.1.0 on Wed Jul  2 23:40:30 2025
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//
#include <wx/wx.h>
#include "indexproperties.h"

// begin wxGlade: ::extracode
// end wxGlade

TableIndex::TableIndex(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: TableIndex::TableIndex
    wxBoxSizer* sizer_1 = new wxBoxSizer( wxHORIZONTAL );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_2 = new wxBoxSizer( wxVERTICAL );
    sizer_1->Add( sizer_2, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    wxGridSizer* grid_sizer_1 = new wxGridSizer( 1, 2, 0, 5 );
    sizer_2->Add( grid_sizer_1, 1, wxEXPAND, 0 );
    list_box_1 = new wxListBox( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, nullptr, wxLB_SINGLE );
    grid_sizer_1->Add( list_box_1, 0, wxEXPAND, 0 );
    wxBoxSizer* sizer_3 = new wxBoxSizer( wxVERTICAL );
    grid_sizer_1->Add( sizer_3, 1, wxEXPAND, 0 );
    m_edit = new wxButton( this, wxID_ANY, _( "&Edit..." ) );
    m_edit->Enable( false );
    sizer_3->Add( m_edit, 0, 0, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    m_new = new wxButton( this, wxID_ANY, _( "&New..." ) );
    sizer_3->Add( m_new, 0, 0, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    m_delete = new wxButton( this, wxID_ANY, _( "&Delete" ) );
    m_delete->Enable( false );
    sizer_3->Add( m_delete, 0, 0, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    
    SetSizer( sizer_1 );
    sizer_1->Fit( this );
    // end wxGlade
    list_box_1->Bind( wxEVT_LISTBOX, &TableIndex::OnIndexSelected, this );
}

void TableIndex::OnIndexSelected(wxCommandEvent &event)
{
    m_edit->Enable( true );
    m_delete->Enable( true );
}
