// -*- C++ -*-
//
// generated by wxGlade 0.9.6 on Sat Jul 25 21:40:51 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//
#include <wx/wx.h>
#include <wx/image.h>
#include "wx/filepicker.h"
#include "wx/statbmp.h"
#include "propertypagebase.h"
#include "pointerproperty.h"

// begin wxGlade: ::extracode
// end wxGlade



PointerPropertiesPanel::PointerPropertiesPanel(wxWindow* parent, const wxString &cursorFile, int stockCursor):
    PropertyPageBase(parent)
{
    m_cursorFile = cursorFile;
    m_stockCursor = stockCursor;
    // begin wxGlade: PointerPropertiesPanel::PointerPropertiesPanel
    filepicker = new wxFilePickerCtrl( this, wxID_ANY );
    const wxString m_pointers_choices[] = {
        "AppStarting!",
        "Arrow!",
        "Cross!"
        "Help!",
        "HourGlass!",
        "Beam!",
        "Icon!",
        "No!",
        "Size!",
        "SizeNESW!",
        "SizeNS!",
        "SizeNWSE!",
        "SizeWE!",
        "UpArrow!"
    };
    m_pointers = new wxListBox( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 14, m_pointers_choices, wxLB_SINGLE );
    m_pointer = new wxStaticBitmap( this, wxID_ANY, wxNullBitmap );
    set_properties();
    do_layout();
    // end wxGlade
    m_pointers->Bind( wxEVT_LISTBOX, &PointerPropertiesPanel::OnPointerSelected, this );
}


void PointerPropertiesPanel::set_properties()
{
    // begin wxGlade: PointerPropertiesPanel::set_properties
    // end wxGlade
    if( m_stockCursor != wxNOT_FOUND )
        m_pointers->SetSelection( m_stockCursor );
    filepicker->SetPath( m_cursorFile );
}


void PointerPropertiesPanel::do_layout()
{
    // begin wxGlade: PointerPropertiesPanel::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer( wxHORIZONTAL );
    wxBoxSizer* sizer_2 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer* sizer_3 = new wxBoxSizer( wxVERTICAL );
    wxBoxSizer* sizer_4 = new wxBoxSizer( wxHORIZONTAL );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    wxStaticText* m_label1 = new wxStaticText(this, wxID_ANY, wxT("Pointer Name"));
    sizer_3->Add( m_label1, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_3->Add( filepicker, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 15, 0, wxEXPAND, 0 );
    wxStaticText* m_label2 = new wxStaticText(this, wxID_ANY, wxT("Stock Pointers:"));
    sizer_3->Add( m_label2, 0, wxEXPAND, 0 );
    sizer_3->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_4->Add( m_pointers, 0, wxEXPAND, 0 );
    sizer_4->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_4->Add( m_pointer, 0, wxALIGN_CENTER_VERTICAL, 0 );
    sizer_3->Add( sizer_4, 0, wxEXPAND, 0 );
    sizer_2->Add( sizer_3, 0, wxEXPAND, 0 );
    sizer_2->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer_1->Add( sizer_2, 0, wxEXPAND, 0 );
    sizer_1->Add( 5, 5, 0, wxEXPAND, 0 );
    SetSizer( sizer_1 );
    sizer_1->Fit( this );
    // end wxGlade
}

void PointerPropertiesPanel::OnPointerSelected(wxCommandEvent &event)  // wxGlade: PointerPropertiesPanel.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (PointerPropertiesPanel::OnPointerSelected) not implemented yet"));
}


// wxGlade: add PointerPropertiesPanel event handlers

