// -*- C++ -*-
//
// generated by wxGlade 0.9.6 on Sat Jul 25 21:40:51 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef POINTERPROPERTY_H
#define POINTERPROPERTY_H

class WXEXPORT PointerPropertiesPanel: public PropertyPageBase
{
public:
    // begin wxGlade: PointerPropertiesPanel::ids
    // end wxGlade

    PointerPropertiesPanel(wxWindow* parent, const wxString &cursorFile, int stockCursor);
    virtual ~PointerPropertiesPanel() { }

private:
    // begin wxGlade: PointerPropertiesPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    wxString m_cursorFile;
    int m_stockCursor;

protected:
    // begin wxGlade: PointerPropertiesPanel::attributes
    wxFilePickerCtrl *filepicker;
    wxListBox* m_pointers;
    wxStaticBitmap *m_pointer;
    // end wxGlade
    void OnPointerSelected(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // POINTERPROPERTY_H
