// -*- C++ -*-
//
// generated by wxGlade 1.0.0a7 on Sun Sep 20 12:20:14 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef PRINTSPEC_H
#define PRINTSPEC_H

class WXEXPORT PrintSpec: public PropertyPageBase
{
public:
    // begin wxGlade: PrintSpec::ids
    // end wxGlade

    PrintSpec(wxWindow* parent);
    virtual ~PrintSpec() { }

private:

protected:
    // begin wxGlade: PrintSpec::attributes
    wxTextCtrl* m_name;
    wxTextCtrl* m_leftAlign;
    wxTextCtrl* m_alignRight;
    wxTextCtrl* m_topAlign;
    wxTextCtrl* text_ctrl_1;
    wxTextCtrl* text_ctrl_2;
    wxTextCtrl* text_ctrl_3;
    wxTextCtrl* text_ctrl_4;
    wxCheckBox* checkbox_1;
    wxTextCtrl* text_ctrl_5;
    wxTextCtrl* text_ctrl_6;
    wxCheckBox* checkbox_2;
    wxCheckBox* checkbox_3;
    // end wxGlade
}; // wxGlade: end class


#endif // PRINTSPEC_H
