// -*- C++ -*-
//
// generated by wxGlade 0.7.2 (standalone edition) on Sat Jan 04 11:51:25 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef GROUPBYPAGE_H
#define GROUPBYPAGE_H

class WXEXPORT SortGroupByPage : public wxPanel
{
public:
    SortGroupByPage(wxWindow *parent);
    ~SortGroupByPage();
protected:
    void set_properties();
    void do_layout();
private:
    wxListCtrl *m_source, *m_dest;
    wxStaticText *m_label;
};

#endif // GROUPBYPAGE_H
