// -*- C++ -*-
//
// generated by wxGlade 0.9.2 on Wed Jul 22 22:08:25 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//
#include <wx/wx.h>
#include "wx/listctrl.h"
#include "wxsf/ShapeCanvas.h"
#include "database.h"
#include "field.h"
#include "fieldwindow.h"
#include "propertypagebase.h"
#include "tableprimarykey.h"

TablePrimaryKey::TablePrimaryKey(wxWindow *parent, Database *db, const DatabaseTable *table) : PropertyPageBase( parent, wxID_ANY )
{
    m_isModified = false;
    m_table = table;
    m_db = db;
    m_options = table->GetTableProperties().pkOptions;
    m_foreignKeyColumnsFields = new FieldWindow( this/*, pt1, width1*/ );
    m_label = new wxStaticText( this, wxID_ANY, _( "Table Columns" ) );
    m_fields = new wxListCtrl( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLC_REPORT );
    m_fields->AppendColumn( m_table->GetTableName(), wxLIST_FORMAT_LEFT, wxLIST_AUTOSIZE );
    int row = 0;
    for( std::vector<TableField *>::const_iterator it = m_table->GetFields().begin(); it < m_table->GetFields().end(); it++ )
    {
        m_fields->InsertItem( row++, (*it)->GetFieldName() );
        if( (*it)->IsPrimaryKey() )
        {
            m_fields->SetItemState( m_fields->FindItem( -1, (*it)->GetFieldName() ), wxLIST_STATE_SELECTED, wxLIST_STATE_SELECTED );
            newKey.push_back( (*it)->GetFieldName() );
            m_foreignKeyColumnsFields->AddField( (*it)->GetFieldName() );
        }
    }
    m_fields->SetColumnWidth( 0, wxLIST_AUTOSIZE );
    m_fields->Bind( wxEVT_LEFT_DOWN, &TablePrimaryKey::OnLeftDown, this );
    do_layout();
}

void TablePrimaryKey::do_layout()
{
    auto main = new wxBoxSizer( wxHORIZONTAL );
    auto sizer1 = new wxBoxSizer( wxVERTICAL );
    auto sizer2 = new wxStaticBoxSizer( new wxStaticBox( this, wxID_ANY, "PK Options" ), wxVERTICAL );
    auto sizer3 = new wxBoxSizer( wxHORIZONTAL );
    auto sizer4 = new wxBoxSizer( wxHORIZONTAL );
    auto sizer5 = new wxBoxSizer( wxHORIZONTAL );
    auto sizer6 = new wxBoxSizer( wxHORIZONTAL );
    main->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer1->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer1->Add( m_foreignKeyColumnsFields, 0, wxEXPAND, 0 );
    sizer1->Add( 60, 60, 0, wxEXPAND, 0 );
    sizer1->Add( m_label, 0, wxEXPAND, 0 );
    sizer1->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer3->Add( m_fields, 0, wxEXPAND, 0 );
    sizer3->Add( 5, 5, 0, wxEXPAND, 0 );
    m_label2 = new wxStaticText( sizer2->GetStaticBox(), wxID_ANY, "Name" );
    m_pkName = new wxTextCtrl( sizer2->GetStaticBox(), wxID_ANY, m_options->m_name );
    sizer5->Add( m_label2, 0, wxEXPAND, 0 );
    sizer5->Add( 5, 5, 0, wxEXPAND, 0 );
    sizer5->Add( m_pkName, 0, wxEXPAND, 0 );
    sizer2->Add( sizer5, 0, wxEXPAND, 0 );
    if( m_db->GetTableVector().m_type == L"SQLite" )
    {
        const wxString selections[] =
        {
            "ROLLBACK",
            "ABORT",
            "FAIL",
            "IGNORE",
            "REPLACE"
        };
        m_label1 = new wxStaticText( sizer2->GetStaticBox(), wxID_ANY, "ON CONFLICT" );
        m_conflict = new wxComboBox( sizer2->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, 5, selections );
        m_conflict->SetSelection( std::dynamic_pointer_cast<SQLitePKOptions>( m_options )->m_conflict );
        m_autoincrement = new wxCheckBox( sizer2->GetStaticBox(), wxID_ANY, "AUTOINCREMENT" );
        m_autoincrement->SetValue( std::dynamic_pointer_cast<SQLitePKOptions>( m_options )->m_autoincrement );
        sizer4->Add( m_label1, 0, wxEXPAND, 0 );
        sizer4->Add( 5, 5, 0, wxEXPAND, 0 );
        sizer4->Add( m_conflict, 0, wxEXPAND, 0 );
        sizer2->Add( sizer4, 0, wxEXPAND, 0 );
        sizer2->Add( 5, 5, 0, wxEXPAND, 0 );
        sizer2->Add( m_autoincrement, 0, wxEXPAND, 0 );
    }
    if( ( m_db->GetTableVector().m_type == L"ODBC" && m_db->GetTableVector().m_subtype == L"Microsoft SQL Server" ) ||
        ( m_db->GetTableVector().m_type == L"Microsoft SQL Server" ) )
    {
        m_clustered = new wxCheckBox( sizer2->GetStaticBox(), wxID_ANY, "CLUSTERED" );
        sizer4->Add( m_clustered, 0, wxEXPAND | wxALIGN_CENTER_VERTICAL, 0 );
        sizer2->Add( sizer4, 0, wxEXPAND, 0 );
        m_padIndex = new wxCheckBox( sizer2->GetStaticBox(), wxID_ANY, "PAD_INDEX" );
        sizer2->Add( 5, 5, 0, wxEXPAND, 0 );
        sizer6->Add( m_padIndex, 0, wxEXPAND, 0 );
        sizer2->Add( sizer6, 0, wxEXPAND, 0 );
    }
    if( ( m_db->GetTableVector().m_type == L"ODBC" && m_db->GetTableVector().m_subtype == L"PostreSQL" ) ||
        ( m_db->GetTableVector().m_type == L"PostgreSQL" ) )
    {
        m_label1 = new wxStaticText( sizer2->GetStaticBox(), wxID_ANY, "INCLUDED" );
        sizer4->Add( m_label1, 0, wxEXPAND, 0 );
        m_included = new wxListCtrl( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLC_REPORT );
        m_included->AppendColumn( m_table->GetTableName(), wxLIST_FORMAT_LEFT, wxLIST_AUTOSIZE );
        int row = 0;
        for( std::vector<TableField *>::const_iterator it = m_table->GetFields().begin(); it < m_table->GetFields().end(); it++ )
        {
            m_included->InsertItem( row++, (*it)->GetFieldName() );
        }
        m_included->SetColumnWidth( 0, wxLIST_AUTOSIZE );
        sizer4->Add( m_included, 0, wxEXPAND, 0 );
    }
    sizer3->Add( sizer2, 0, wxEXPAND, 0 );
    sizer1->Add( sizer3, 0, wxEXPAND, 0 );
    main->Add( sizer1, 1, wxEXPAND, 0 );
    main->Add( 5, 5, 0, wxEXPAND, 0 );
    SetSizer( main );
}

void TablePrimaryKey::OnLeftDown(wxMouseEvent &event)
{
    auto flags = wxLIST_HITTEST_ONITEM;
    auto item = m_fields->HitTest( event.GetPosition(), flags );
    if( item != wxNOT_FOUND )
    {
        m_isModified = true;
        auto label = m_fields->GetItemText( item );
        if( m_fields->GetItemState( item, wxLIST_STATE_SELECTED ) == wxLIST_STATE_SELECTED )
        {
            m_fields->SetItemState( item, 0, wxLIST_STATE_SELECTED );
            newKey.erase( std::remove( newKey.begin(), newKey.end(), label ), newKey.end() );
            m_foreignKeyColumnsFields->RemoveField( label );
        }
        else
        {
            m_fields->SetItemState( item, wxLIST_STATE_SELECTED, wxLIST_STATE_SELECTED );
            newKey.push_back( label.ToStdWstring() );
            m_foreignKeyColumnsFields->AddField( label );
        }
    }
}
