// -*- C++ -*- generated by wxGlade 0.5 on Sun Feb 10 01:29:26 2008
/***************************************************************************
 *   Copyright (C) 2005 by Igor Korot                                      *
 *   igor@IgorsGentoo                                                      *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/
#ifndef FONTPROPERTYPAGEBASE_H
#define FONTPROPERTYPAGEBASE_H

struct FontPropertyPage
{
    wxFont font;
    wxColour text, back;

    FontPropertyPage &operator=(const FontPropertyPage &right)
    {
        if( this != &right )
        {
            font = right.font;
            text = right.text;
            back = right.back;
        }
        return *this;
    }
};

#if defined __WXMSW__ || defined __WXGTK__
class WXEXPORT wxFontPreviewer : public wxWindow
{
public:
    wxFontPreviewer(wxWindow *parent, wxString text) : wxWindow( parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE )
    {
        m_text = text;
    }
    void SetFont(FontPropertyPage &font) { m_font = font.font; Refresh(); };
    DECLARE_EVENT_TABLE()
private:
    wxString m_text;
    void OnPaint(wxPaintEvent& event);
};
#endif

class WXEXPORT CFontPropertyPageBase : public PropertyPageBase
{
public:
    CFontPropertyPageBase(wxWindow* parent, const FontPropertyPage &font, int id=wxID_ANY, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);
    ~CFontPropertyPageBase();
    bool IsDirty();
    virtual void SetFont(const std::wstring &name, int size, bool italic, bool bold, bool underline, bool strikethrough);
    virtual FontPropertyPage &GetFont();
    wxString &GetFaceName() const;
    void SetFaceName(const wxString &name);
    wxFontWeight &GetWeight() const;
    int GetPointSize() const;
    bool GetUnderline() const;
    bool GetStrikethrough() const;
    wxFontStyle GetStyle() const;
    void SetFont(FontPropertyPage font) { m_font = font; }
protected:
    wxString m_faceName;
    int m_ptSize;
    wxFontWeight m_weight;
    wxFontStyle m_style;
    FontPropertyPage m_font;
    bool m_dirty, m_underline, m_striken;
};

#if defined( __WXMSW__ )
#include "msw/fontpropertypage.h"
#elif defined( __WXGTK__ )
#include "gtk/fontpropertypageGTK.h"
#elif defined( __WXMAC__ )
#include "cocoa/fontpropertypage.h"
#elif defined(__WXQT__)
#include "qt/fontpropertypageQt.h"
#endif

#endif // FONTPROPERTYPAGE_H
