# CMake generated Testfile for 
# Source directory: C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests
# Build directory: C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(r_strings "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/Debug/strings.exe")
  set_tests_properties(r_strings PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(r_strings "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/Release/strings.exe")
  set_tests_properties(r_strings PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(r_strings "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/MinSizeRel/strings.exe")
  set_tests_properties(r_strings PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(r_strings "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/RelWithDebInfo/strings.exe")
  set_tests_properties(r_strings PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
else()
  add_test(r_strings NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(r_strtok_r "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/Debug/strtok_r.exe")
  set_tests_properties(r_strtok_r PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(r_strtok_r "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/Release/strtok_r.exe")
  set_tests_properties(r_strtok_r PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(r_strtok_r "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/MinSizeRel/strtok_r.exe")
  set_tests_properties(r_strtok_r PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(r_strtok_r "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/RelWithDebInfo/strtok_r.exe")
  set_tests_properties(r_strtok_r PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
else()
  add_test(r_strtok_r NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(r_strsep "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/Debug/strsep.exe")
  set_tests_properties(r_strsep PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(r_strsep "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/Release/strsep.exe")
  set_tests_properties(r_strsep PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(r_strsep "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/MinSizeRel/strsep.exe")
  set_tests_properties(r_strsep PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(r_strsep "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests/RelWithDebInfo/strsep.exe")
  set_tests_properties(r_strsep PROPERTIES  WORKING_DIRECTORY "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/buildWin/src/replacements/unittests" _BACKTRACE_TRIPLES "C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;5;add_test;C:/Users/Igor/OneDrive/Documents/dbhandler_app/freetds/src/replacements/unittests/CMakeLists.txt;0;")
else()
  add_test(r_strsep NOT_AVAILABLE)
endif()
